### ISSUE TITLE
BIP32 private key derivation edge case

### ISSUE THREAD

**Issue by kanzure** [richardkiss/pycoin#103]
Regarding this section of BIP32:
https://github.com/bitcoin/bips/blob/2ea19daaa0380fed7a2b053fd1f488fadba28bda/bip-0032.mediawiki#private-parent-key--private-child-key

> In case parse256(IL) ≥ n or ki = 0, the resulting key is invalid, and one should proceed with the next value for i. (Note: this has probability lower than 1 in 2^(127).)

In particular I suspect this should be implemented near:
https://github.com/richardkiss/pycoin/blob/5ebd6c038eb5de5ee5330eea70887ddd4ba390ce/pycoin/key/BIP32Node.py#L232

Alternatively, what about raising an error instead? I know this is not standards-compliant, but if someone really needs that functionality they can just increment the value themselves and try again, I believe.

**Comment by posita** [comment]
> Alternatively, what about raising an error instead? I know this is not standards-compliant, but if someone really needs that functionality they can just increment the value themselves and try again, I believe.

:+1: for raising an exception in this case.

The caller should probably know whether the subkey at a particular index is invalid and be responsible for skipping it. (By the way, I'm pretty sure this is exactly what the standard calls for.) Consider the case where index `x` is invalid if one *didn't* raise an exception:

```python
i = x - 1
subkey = node.subkey(i) # returns subkey for x -1
i = x
subkey = node.subkey(i) # silently returns subkey for x + 1
i = x + 1
subkey = node.subkey(i) # returns already-seen subkey
```

If one were to silently move onto the next valid key, then the caller has to perform at least one look-ahead to make sure a distinct subkey is returned for every single call to `subkey`. This is probably not what you want.

**Comment by posita** [comment]
Note that there's a similar edge condition for public parent key to public child key derivation. From https://github.com/bitcoin/bips/blob/2ea19daaa0380fed7a2b053fd1f488fadba28bda/bip-0032.mediawiki#public-parent-key--public-child-key:

> In case parse<sub>256</sub>(I<sub>L</sub>) ≥ n or K<sub>i</sub> is the point at infinity, the resulting key is invalid, and one should proceed with the next value for i.

I haven't yet investigated how pycoin's ECDSA implementation represents K<sub>i</sub> "at infinity".... :bowtie:

**Comment by posita** [comment]
Has anyone found a test vector for these cases yet? (I know these are very rare.) BIP32 [has none](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#test-vectors). The [bitcoin](/bitcoin/bitcoin) reference implementation only uses the [original test vectors](https://github.com/bitcoin/bitcoin/blob/164d7b674b49b3c062d0331f28d21ad4f6bf5207/src/test/bip32_tests.cpp), [as does bitcoinj](https://github.com/bitcoinj/bitcoinj/blob/e0870efd61e19b971664aaaea384e9e1cebcc7ae/core/src/test/java/org/bitcoinj/crypto/BIP32Test.java).

**Comment by posita** [comment]
I'm thinking the right approach is to either raise exceptions from [`subkey_secret_exponent_chain_code_pair`](https://github.com/richardkiss/pycoin/blob/5ebd6c038eb5de5ee5330eea70887ddd4ba390ce/pycoin/key/bip32.py#L53) and [`subkey_public_pair_chain_code_pair`](https://github.com/richardkiss/pycoin/blob/5ebd6c038eb5de5ee5330eea70887ddd4ba390ce/pycoin/key/bip32.py#L89), or return `(None, None)` from those functions, and then raise exceptions from [`BIP32Node._subkey(...)`](https://github.com/richardkiss/pycoin/blob/5ebd6c038eb5de5ee5330eea70887ddd4ba390ce/pycoin/key/BIP32Node.py#L175).

**Comment by posita** [comment]
@kanzure, check out PR #108. As far as skipping bad keys is concerned, I didn't add any convenience functions to `BIP32Node`, but I did [augment the `ku` script](https://github.com/posita/pycoin/blob/key-verification-103/pycoin/scripts/ku.py#L218) to keep trying in the (incredibly unlucky) event of stumbling onto a bad subkey.

Anyway, let me know what you think.
