### ISSUE TITLE
Several ported bitcoin tests failing

### ISSUE THREAD

**Issue by posita** [richardkiss/pycoin#114]
Here's the list (originally from this https://github.com/richardkiss/pycoin/issues/112#issuecomment-89798230):

* [`"The following tests for the presence of a bug in the handling of SIGHASH_SINGLE"`](https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/tests/data/tx_valid.json#L32)
* [`"Empty pubkey"`](https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/tests/data/tx_valid.json#L82)
* [`"Empty signature"` (index 1)](https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/tests/data/tx_valid.json#L90)
* [`"Empty signature"` (index 2)](https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/tests/data/tx_valid.json#L93)

These tests are failing, but their failures are being hidden by #112.

**Comment by richardkiss** [comment]
I believe these are all passing in 0.62.

**Comment by posita** [comment]
@richardkiss, sorry for the confusion. The tests were failing, but their failures were being hidden (see #112). #113 exposes these failures (but that PR suffered from not being timely merged). I will attempt to update that PR.

The purpose of this issue is to be able to merge #113 and close #112, but still track the failing tests whose failures would finally be exposed by that merge. Perhaps this should be closed and #112 should remain (even after merging #113)?

**Comment by richardkiss** [comment]
I'm pretty sure that these test are passing properly now, as the necessary functionality in #113 is committed

**Comment by posita** [comment]
LGTM :+1: Apologies for missing that.
