### ISSUE TITLE
Question: is failing on an empty `scriptSig` stack the right thing?

### ISSUE THREAD

**Issue by posita** [richardkiss/pycoin#115]
From `vm.py` (lines [149](https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/pycoin/tx/script/vm.py#L149) and [140](https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/pycoin/tx/script/vm.py#L140)):

```py
def eval_script(script, signature_for_hash_type_f, expected_hash_type=None, stack=[],
                disallow_long_scripts=True):
    ...
    return len(stack) != 0 # only succeeds if stack has something there


def verify_script(script_signature, script_public_key, signature_for_hash_type_f, expected_hash_type=None):
    ...
    # this fails if script_signature is empty, but we're still going to evaluate script_public_key later
    if not eval_script(script_signature, signature_for_hash_type_f, expected_hash_type, stack):
        logger.debug("script_signature did not evaluate")
        return False
    ...
```

Is it technically invalid to have an empty `scriptSig` stack? Granted, it's probably a dumb idea, but does it violate the protocol?

**Comment by richardkiss** [comment]
I think this corresponds to https://github.com/bitcoin/bitcoin/blob/master/src/script/interpreter.cpp#L1174

**Comment by posita** [comment]
Res, it does appear to correspond to that line, but the issue is whether an empty script is valid. I believe the answer is "no". From <https://en.bitcoin.it/wiki/Script>:

> A transaction is valid if nothing in the combined script triggers failure and the top stack item is true (non-zero).

So it is appropriate to close this, but I wanted to be clear that failing on an empty stack is the correct behavior.

**Comment by posita** [comment]
Res, it does appear to correspond to that line, but the issue is whether an empty scriptSig stack can be valid. I believe the answer is "possibly". From <https://en.bitcoin.it/wiki/Script> (***emphasis*** added):

> A transaction is valid if nothing in the ***combined*** script triggers failure and the top stack item is true (non-zero).

So it is appropriate to close this with the changes since this issue was filed, but I wanted to be clear as to why.

**Comment by posita** [comment]
Yes, it does appear to correspond to that line, but the issue is whether an empty `scriptSig` stack can be valid. I believe the answer is "possibly". From <https://en.bitcoin.it/wiki/Script> (***emphasis*** added):

> A transaction is valid if nothing in the ***combined*** script triggers failure and the top stack item is true (non-zero).

It looks like the behavior of `eval_script` is correct (although I can't quite figure out why from looking at the code):

```py
>>> from pycoin.tx.script.vm import eval_script
>>> stack = []
>>> eval_script('', None, stack)
True
>>> stack
[]
```

So I think it is appropriate to close this, but I wanted to be clear as to why. On a side note, a ***combined*** empty stack looks like it will fail (as it should), specifically because `verify_script` will raise an `IndexError` (see [vm.py#L162](https://github.com/richardkiss/pycoin/blob/df0e3d9366332a261bc9998bff4ea38d25df08e5/pycoin/tx/script/vm.py#L162).

**Comment by posita** [comment]
Yes, it does appear to correspond to that line, but the issue is whether an empty `scriptSig` stack can be valid. I believe the answer is "possibly". From <https://en.bitcoin.it/wiki/Script> (***emphasis*** added):

> A transaction is valid if nothing in the ***combined*** script triggers failure and the top stack item is true (non-zero).

~~It looks like the behavior of `eval_script` is correct (although I can't quite figure out why from looking at the code):~~ ***UPDATE: The behavior of `eval_script` in 0.62 is*** **not** ***correct.*** *(I mistakenly tried it with 0.53 before, which has the right behavior).* ***0.62 does not behave correctly***:

```py
% pip show pycoin
---
Metadata-Version: 2.0
Name: pycoin
Version: 0.62
Summary: Utilities for Bitcoin and altcoin addresses and transaction manipulation.
Home-page: https://github.com/richardkiss/pycoin
Author: Richard Kiss
Author-email: him@richardkiss.com
License: http://opensource.org/licenses/MIT
Location: /.../lib/python2.7/site-packages
Requires:
% python
Python 2.7.10 (default, Sep 24 2015, 10:13:45)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycoin
>>> pycoin.__file__
'/.../lib/python2.7/site-packages/pycoin/__init__.pyc'
>>> from pycoin.tx.script.vm import eval_script
>>> stack = []
>>> assert eval_script('', None, stack) == True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> stack
[]
```

~~So I think it is appropriate to close this, but I wanted to be clear as to why.~~ ***UPDATE: I think this should be reopened.*** On a side note, *if this were fixed* a ***combined*** empty stack looks like it will *still* fail (as it should), specifically because `verify_script` will raise an `IndexError` (see [vm.py#L162](https://github.com/richardkiss/pycoin/blob/df0e3d9366332a261bc9998bff4ea38d25df08e5/pycoin/tx/script/vm.py#L162)).

**Comment by posita** [comment]
> I think this corresponds to https://github.com/bitcoin/bitcoin/blob/master/src/script/interpreter.cpp#L1174

@richardkiss, it does not. The line you cited is in `VerifyScript`. The line I identified originally is in pycoin's analogy to [`EvalScript`](https://github.com/bitcoin/bitcoin/blob/master/src/script/interpreter.cpp#L229). More specifically, this is the change that needs to happen:

```diff
diff --git a/pycoin/tx/script/vm.py b/pycoin/tx/script/vm.py
index bb6589d..7dd9337 100644
--- a/pycoin/tx/script/vm.py
+++ b/pycoin/tx/script/vm.py
@@ -138,7 +138,7 @@ def eval_script(script, signature_for_hash_type_f, expected_hash_type=None, stac
         logger.exception("script failed for unknown reason")
         return False

-    return len(stack) != 0
+    return True


 def verify_script(script_signature, script_public_key, signature_for_hash_type_f, expected_hash_type=None):
@@ -151,6 +151,9 @@ def verify_script(script_signature, script_public_key, signature_for_hash_type_f
         logger.debug("script_signature did not evaluate")
         return False

+    if len(stack) == 0:
+        return False
+
     if is_p2h:
         signatures, alt_script_public_key = stack[:-1], stack[-1]
         alt_script_signature = bin_script(signatures)
```

I have opened PR #159 for this change.

Apologies for any confusion. I should have investigated more fully and more carefully before commenting previously.
