### ISSUE TITLE
Question: should validation be different for signature creation vs. validation?

### ISSUE THREAD

**Issue by posita** [richardkiss/pycoin#118]
There is code present that is present for the purpose of supporting non-standard or legacy transactions. Here are some examples:
- https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/pycoin/tx/Tx.py#L183
- https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/pycoin/tx/script/check_signature.py#L133
- https://github.com/richardkiss/pycoin/blob/b2dd44f5674913cae08a4079c76797b6d3bfeae4/pycoin/tx/script/vm.py#L51 (see `disallow_long_scripts` argument)

There are other cases where transactions may be valid according the protocol and may make it into blocks, but probably shouldn't be relayed or be created by modern tool kits. One of the most well known examples is the pop-one-too-many bug with `OP_CHECKMULTISIG`. Technically, it doesn't matter what the value is, but modern implementations enforce `OP_0` to avoid malleability. So a transaction using (e.g.) `OP_1` instead of `OP_0` in a block should probably be treated as valid, but being relayed from a peer should probably be accepted into the memory pool, but not re-relayed.

All of this puts tool kits in an awkward position where validation of some transactions should be more lenient than others (e.g., those created by the tool kit itself).

pycoin's support for this bifurcated validation (where it exists) is somewhat ad hoc. In fairness, even in `bitcoind`, there's an awkward `flags` argument that is used for this purpose (see [here](https://github.com/bitcoin/bitcoin/blob/fcf646c9b08e7f846d6c99314f937ace50809d7a/src/script/standard.h#L32) and [here](https://github.com/bitcoin/bitcoin/blob/41e6e4caba9899ce7c165b0784461c55c867ee24/src/script/interpreter.cpp#L238)).

I'm opening this issue merely to open the discussion regarding:
1. Whether this should be addressed at all; and
2. How best to do it.

**Comment by richardkiss** [comment]
I'd like to create a list PayFrom classes that correspond to PayTo classes that do more examination and validation of the ```TxIn``` scripts. One feature of these could be to determine whether the script meets the necessary level of "standardness" to be propagated, which as you mention, is a different criteria than simply validating.

This would be a good place for ```who_signed_this```-type functionality, as well as parsing other metadata that's specific to a certain type of transaction, and would allow it to be extensible in a handy way that would make it easy to experiment with new types of transactions.

**Comment by richardkiss** [comment]
I think the correct answer is to create a new function ```is_transaction_standard``` which uses a different set of flags when validating transactions. This will be a lot easier using ```Tx.check_solution``` introduced at 8c13da5d.
