### ISSUE TITLE
Exception while signing transaction using command line tool. 

### ISSUE THREAD

**Issue by fabiomssilva** [richardkiss/pycoin#121]
Hi, 

I was playing around with command line tools on the tutorial and I found a issue. 

I try to create a transaction with the tx command line tool . And I get this stack trace. 
the file "mikey" have the WIF on line 1. 
I also try to insert directly the WIF on the command line (without the "-f mikey") and I get the same result. 

C:\Users\me\Desktop\pycoin-master\pycoin\scripts>tx -F 1000 -i 19YzTHxw
1EKe5TfgfeLEyfB9RgScYngFMH 18DeVTA6UL3VnTNgJ4DCXoYH2oxiqSfMnA -f mikey
signing...
Traceback (most recent call last):
  File "C:\Users\fabio.silva\Desktop\pycoin-master\pycoin\scripts\tx.py", line 514, in <module>
    main()
  File "C:\Users\fabio.silva\Desktop\pycoin-master\pycoin\scripts\tx.py", line 443, in main
    sign_tx(tx, wif_iter(key_iters), p2sh_lookup=p2sh_lookup)
  File "build\bdist.win-amd64\egg\pycoin\tx\tx_utils.py", line 170, in sign_tx
  File "build\bdist.win-amd64\egg\pycoin\tx\Tx.py", line 381, in sign
    smaller = min(len(tx.txs_in), len(tx.txs_out))
  File "build\bdist.win-amd64\egg\pycoin\tx\Tx.py", line 256, in sign_tx_in
    #   potential_addresses = address_re.findall(line)
  File "build\bdist.win-amd64\egg\pycoin\tx\pay_to\ScriptUnknown.py", line 16, in solve NameError: global name 'SolvingError' is not defined

Tnks!

**Comment by richardkiss** [comment]
I haven't tested extensively on Windows. There are a couple problems here; "SolvingError" is not imported from any of the pay_to/Script*.py files. But also, this incoming TxIn should be recognized as a ScriptPayToAddress, not a ScriptUnknown. This may be a Windows-specific problem.

**Comment by richardkiss** [comment]
Any chance you can try this on a UNIX machine (Linux or Mac)?

**Comment by richardkiss** [comment]
As a baseline, on Windows, try:

    $ echo KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn > pk1
    $ tx -F 1000 8c9a296b5cd10e9eb118b66424a4d3fec9474f500fa5b6f9a982e5eacc5b036d/0/76a914751e76e8199196d454941c45d1b3a323f1433bd688ac/25000 18DeVTA6UL3VnTNgJ4DCXoYH2oxiqSfMnA -f pk1

This creates a properly signed transaction on a Mac. Does it on Windows?

**Comment by fabiomssilva** [comment]
Hi, 

Tested in a Ubuntu Server Linux installation. 

Linux xxhostnamexxx 2.6.32-042stab104.1 #1 SMP Thu Jan 29 12:58:41 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

with python 
Python 2.7.6 (x64)

And the result was the same. 
I am thinking 2 things:

1)
64 vs 32 bits python. But I think this would have been detected by now :) 

2)
My instalation procedure. 
What I am doing to install pycoin is run:
setup.py install 

Then executing tx. 

Tryed to execute from /usr/local/bin/tx
And also from tx.py from the scripts directory


/usr/local/bin/tx  -F 1000 8c9a296b5cd10e9eb118b66424a4d3fec9474f500fa5b6f9a982e5eacc5b036d/0/76a914751e76e8199196d454941c45d1b3a323f1433bd688ac/25000 18DeVTA6UL3VnTNgJ4DCXoYH2oxiqSfMnA -f pk1
signing...
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 9, in <module>
    load_entry_point('pycoin==0.53', 'console_scripts', 'tx')()
  File "build/bdist.linux-x86_64/egg/pycoin/scripts/tx.py", line 444, in main
  File "build/bdist.linux-x86_64/egg/pycoin/tx/tx_utils.py", line 170, in sign_tx
  File "build/bdist.linux-x86_64/egg/pycoin/tx/Tx.py", line 381, in sign
  File "build/bdist.linux-x86_64/egg/pycoin/tx/Tx.py", line 256, in sign_tx_in
  File "build/bdist.linux-x86_64/egg/pycoin/tx/pay_to/ScriptPayToAddress.py", line 52, in solve
NameError: global name 'SolvingError' is not defined

Any idea what might be happening ?

**Comment by akaihola** [comment]
The `SolvingError` class is not imported in `ScriptPayToAddress.py`, so throwing a more descriptive error message fails. It's also not possible to import it at the top since that would cause an import loop. @richardkiss, I suggest creating a separate `pycoim/tx/pay_to/exceptions.py` module and moving `SolvingError` there.

**Comment by richardkiss** [comment]
@akaihola fix is in cc7f10fe4e26f353218fd884e89d263f2efb6dc1

**Comment by richardkiss** [comment]
@fabiomssilva my best guess is that you don't have the correct WIF for your source transactions in your mikey file. In any case, as of master, you won't get that annoying incorrect exception.
