### ISSUE TITLE
Nulldata / OP_RETURN data not a transaction type

### ISSUE THREAD

**Issue by XertroV** [richardkiss/pycoin#122]
Nulldata / OP_RETURN transactions are not a recognised type like pay-to-address or pay-to-hash transactions are (and other types included in the pycoin/tx/pay_to directory). There is value in recognising these transaction types as it allows better parsing, matching, and processing of real-world outputs, as well as the ability to craft more complex transactions with a wider applicability set, thus increasing the utility of pycoin.

**Comment by XertroV** [comment]
I tried to link my recent pull request (https://github.com/richardkiss/pycoin/pull/123) to this but seem to have failed.

**Comment by richardkiss** [comment]
Great patch, thanks!
