### ISSUE TITLE
Recreating Gavin's MultiSig TwoOfThree.sh referance implimentation.

### ISSUE THREAD

**Issue by MineForeman** [richardkiss/pycoin#125]
Hi All,

I am trying (and filing) to recreate the referance multisig addresss from Gavin (https://gist.github.com/gavinandresen/3966071) .

It is my fault but I would like some pointers if possible, the code I am using is;-

    from pycoin.tx.pay_to import ScriptMultisig, address_for_pay_to_script

    keys = [
        "0491bba2510912a5bd37da1fb5b1673010e43d2c6d812c514e91bfa9f2eb129e1c183329db55bd868e209aac2fbc02cb33d98fe74bf23f0c235d6126b1d8334f86",
        "04865c40293a680cb9c020e7b1e106d8c1916d3cef99aa431a56d253e69256dac09ef122b1a986818a7cb624532f062c1d1f8722084861c5c3291ccffef4ec6874",
         "048d2455d2403e08708fc1f556002f1b6cd83f992d085097f9974ab08a28838f07896fbab08f39495e15fa6fad6edbfb1e754e35fa1c7844c41f322a1863d46213",
    ]

    generated_address = address_for_pay_to_script(ScriptMultisig(2, keys).script())
    from_page ='3QJmV3qfvL9SuYo34YihAf3sRCW3qSinyC'

    if generated_address == from_page:
        print('It worked')
    else:
        print('You fail')

In the above instance I am getting back 3FB66msrsz6egVRue8JxnUfXPW8nACQsr6 and not the expected 3QJmV3qfvL9SuYo34YihAf3sRCW3qSinyC.

Needless to say, I am getting a log of "You fail" messages.  I suspect it is because I am not encoding the sec keys properly but for the life of my I cannot work out how I should be doing it.

Any chance for a friendly tip?

Neil

**Comment by MineForeman** [comment]
Got it!

As I suspected, I was not encoding the sec keys correctly.  I needed to 'unhexlfy' back to binary, if anyone in the future has the same problem/question here is the complete working code;-

    from pycoin.tx.pay_to import ScriptMultisig, address_for_pay_to_script
    import binascii

    keys = [
        binascii.unhexlify("0491bba2510912a5bd37da1fb5b1673010e43d2c6d812c514e91bfa9f2eb129e1c183329db55bd868e209aac2fbc02cb33d98fe74bf23f0c235d6126b1d8334f86"),
        binascii.unhexlify("04865c40293a680cb9c020e7b1e106d8c1916d3cef99aa431a56d253e69256dac09ef122b1a986818a7cb624532f062c1d1f8722084861c5c3291ccffef4ec6874"),
        binascii.unhexlify("048d2455d2403e08708fc1f556002f1b6cd83f992d085097f9974ab08a28838f07896fbab08f39495e15fa6fad6edbfb1e754e35fa1c7844c41f322a1863d46213"),
    ]

    generated_address = address_for_pay_to_script(ScriptMultisig(2, keys).script())
    from_page ='3QJmV3qfvL9SuYo34YihAf3sRCW3qSinyC'

    if generated_address == from_page:
        print('It worked')
    else:
        print('You fail')

Closing.

**Comment by reiven** [comment]
Hi @MineForeman is this the pycoin version of 2of3 online somewhere? I see no documentation on how to use multisig with pycoin
Thanks

**Comment by richardkiss** [comment]
Take a look in https://github.com/richardkiss/pycoin/tree/master/recipes/multisig for a multisig recipe. There is a lot going on.
