### ISSUE TITLE
"public key has no private parts" error

### ISSUE THREAD

**Issue by derrend** [richardkiss/pycoin#129]
When following this guide: http://blog.richardkiss.com/?p=313&cpage=1
at line `genwallet -f master-private-key -s .pub > master-public-key` I am given the output `public key has no private parts`.

Please can someone let me know what I am doing wrong. I have tried in several environments so far and python versions 2.7 to 3.4.
I'm using docker in case that is important.

Update:
Whilst experimenting I am also encountering other errors such as -
```
root@server:~# genwallet -i -k xprv9s21ZrQH143K2CuijKf2R5F1iUyqq48b92kWxs6br4Zp7EA8VCzQPx8Kh8jszFeNGTMsUdt4mU17Lt263bGKCVMi7byAZazgbPKhv7zWGBN
xprv9s21ZrQH143K2CuijKf2R5F1iUyqq48b92kWxs6br4Zp7EA8VCzQPx8Kh8jszFeNGTMsUdt4mU17Lt263bGKCVMi7byAZazgbPKhv7zWGBN
Traceback (most recent call last):
  File "/usr/local/bin/genwallet", line 9, in <module>
    load_entry_point('pycoin==0.52', 'console_scripts', 'genwallet')()
  File "/usr/local/lib/python2.7/dist-packages/pycoin/scripts/genwallet.py", line 99, in main
    print(full_network_name_for_netcode(wallet.netcode))
AttributeError: 'BIP32Node' object has no attribute 'netcode'
```

**Comment by richardkiss** [comment]
The document https://github.com/richardkiss/pycoin/blob/master/COMMAND-LINE-TOOLS.md is an updated version of this blog post that uses ```ku``` which is a better version of ```genwallet```, which is deprecated. Try walking through that instead.

**Comment by derrend** [comment]
Tank you for the response.

One question regarding `ku` is there a correct way to generate subkeys on the fly from a secret exponent? The example below gives me the error below,
'''
ku 51278415111548370968506974910502378737664866669958726520919747362341485249057 -s 0/0-5 -w
Traceback (most recent call last):
  File "/usr/bin/ku", line 9, in <module>
    load_entry_point('pycoin==0.52', 'console_scripts', 'ku')()
  File "/usr/lib/python2.7/site-packages/pycoin/scripts/ku.py", line 275, in main
    print(output_dict["wallet_key"])
KeyError: 'wallet_key'
'''

**Comment by richardkiss** [comment]
A secret exponent corresponds to a WIF, a single key. To generate subkeys, you must start from a BIP32 node.

    $ ku P:foo -s0/0-5 -W
    L5a4iE5k9gcJKGqX3FWmxzBYQc29PvZ6pgBaePLVqT5YByEnBomx
    Kyjgne6GZwPGB6G6kJEhoPbmyjMP7D5d3zRbHVjwcq4iQXD9QqKQ
    L4B3ygQxK6zH2NQGxLDee2H9v4Lvwg14cLJW7QwWPzCtKHdWMaQz
    L2L2PZdorybUqkPjrmhem4Ax5EJvP7ijmxbNoQKnmTDMrqemY8UF
    L2oD6vA4TUyqPF8QG4vhUFSgwCyuuvFZ3v8SKHYFDwkbM765Nrfd
    KzChTbc3kZFxUSJ3Kt54cxsogeFAD9CCM4zGB22si8nfKcThQn8C

**Comment by derrend** [comment]
Ok I see.

What if I just want the keys, or the addresses,
```
ku 51278415111548370968506974910502378737664866669958726520919747362341485249057 -s 0/0-5 -a
198HXaicwuVZLc3ajFSrWSmEG53KAfhuqq
```
I'm only given the first iteration?

**Comment by richardkiss** [comment]
In this example, you're again using a secret exponent which creates a Key object. A Key does not have children. Only BIP32 nodes have children. Use ```ku P:passphrase -w``` or ```ku create -w``` to create a BIP32 node.

**Comment by derrend** [comment]
Ok thank you. Still developing my intuition for these keys :)
