### ISSUE TITLE
is_valid_bitcoin_address() fails for multisig addresses

### ISSUE THREAD

**Issue by shayanb** [richardkiss/pycoin#130]
This function returns false for some (if not all) multisig addresses.

https://github.com/richardkiss/pycoin/blob/master/pycoin/encoding.py#L296

**Comment by richardkiss** [comment]
Yes, this description for this function should be improved. You should use is_address_valid  in https://github.com/richardkiss/pycoin/blob/master/pycoin/key/validate.py#L77 instead.

**Comment by shayanb** [comment]
thanks, is_address_valid() apparently works for now. I guess we should remove one just to make it less complicated!
