### ISSUE TITLE
script_signature did not evaluate

### ISSUE THREAD

**Issue by lekanovic** [richardkiss/pycoin#132]
When I try to sign a transaction I get a message from pycoin:
DEBUG:pycoin.tx.script.vm:script_signature did not evaluate

What I don't understand is if I send this transaction to the bitcoin network it is accepted. I thought this error message meant that I have used incorrect private keys to sign the transaction and was therefore a invalid transaction. But this cannot be since my transaction is accepted by the network(Testnet).

So what does this error message mean?

**Comment by richardkiss** [comment]
This output is from https://github.com/richardkiss/pycoin/blob/master/pycoin/tx/script/vm.py#L151 and it means that the script_signature (the redeem script) is probably blank. When you go to sign a transaction, pycoin first checks if it is already signed. In your case, the redeem script is blank, so this message is printed to the logger. Then the transaction is signed.
