### ISSUE TITLE
Pycoin gets incorrect output address from rawtx?

### ISSUE THREAD

**Issue by F483** [richardkiss/pycoin#136]
# testnet txid and corresponding rawtx
    # see https://test-insight.bitpay.com/tx/e20af2349c48774eddda161b74659e3e64ad0f62794df9a2271e6baa313796f2
    txid = "e20af2349c48774eddda161b74659e3e64ad0f62794df9a2271e6baa313796f2"
    rawtx = "010000000120addc4fc706417fad4158b4b9e30f9289e7dac4918277dc189e03f9a0155064000000006b483045022100b49bae1352d24d9673396bb01a23da583e01c5226347be6cf0f75477cce7f628022062eeb7a5a9b87a97f834660ce417278d4889d525e7e0f947020efdda045d54530121028895b78ad435814caecbeeb43453e4881a96d32c23d61b909dee06ad44c07ad5ffffffff0273a139c3000000001976a914a6d608497ad283ca93c1bdc3abb0a610b8edb18988ac80a81201000000001976a914f4131906b10615a61af347c56f1223ddc214f95c88ac00000000"

    from pycoin.tx.Tx import Tx # pycoin 0.52

    tx = Tx.tx_from_hex(rawtx)
    out = tx.txs_out[1]

    print "expected", "n3mW3o8XNMyH6xHWBkN98rm7zxxxswzpGM"
    print "actually", out.bitcoin_address()

    # OUTPUT
    # expected n3mW3o8XNMyH6xHWBkN98rm7zxxxswzpGM
    # actually 1PFYkk3YZLY2KqotUBPmJwYo8yNFz3Nxyy

**Comment by shayanb** [comment]
you have to use netcode argument in bitcoin_address(netcode=netcode) to get the correct address
```
tx_out.bitcoin_address(netcode='XTN')
```

**Comment by F483** [comment]
Thanks. Though it doesn't solve my problem, I guess I isolated it badly. I'm actually trying to sign a transaction.

    from pycoin.tx.script import tools                                           
    from pycoin.serialize import b2h, h2b, b2h_rev, h2b_rev                      
    from pycoin.tx.pay_to import build_hash160_lookup                            
    from pycoin.tx import SIGHASH_ALL                                            
                                                                                 
                                                                                 
    def signtx(service, testnet, tx, secretexponents):                           
        lookup = build_hash160_lookup(secretexponents)                           
        for txin_idx in xrange(len(tx.txs_in)):                                  
            txin = tx.txs_in[txin_idx]                                           
            utxo_tx = service.get_tx(txin.previous_hash)                         
            script = utxo_tx.txs_out[txin.previous_index].script                 
            tx.sign_tx_in(lookup, txin_idx, script, SIGHASH_ALL)
        return tx

The error I get.

  File "/home/fabe/dev/btctxstore/btctxstore/control.py", line 20, in signtx
    tx.sign_tx_in(lookup, txin_idx, script, SIGHASH_ALL)
  File "build/bdist.linux-x86_64/egg/pycoin/tx/Tx.py", line 232, in sign_tx_in
    existing_script=self.txs_in[tx_in_idx].script, **kwargs)
  File "build/bdist.linux-x86_64/egg/pycoin/tx/pay_to/ScriptPayToAddress.py", line 52, in solve
    raise SolvingError("can't find secret exponent for %s" % self.address())
NameError: global name 'SolvingError' is not defined
