### ISSUE TITLE
Question: How to import and use ku in different script

### ISSUE THREAD

**Issue by twig123** [richardkiss/pycoin#140]
Hello,

I'm trying to use ku to change a Compressed Private Key into an Uncompressed Private Key, however, the process of having to call `ku.py -u -W {CompressedPrivateKey}` from another script is very slow, as it has to start the ku.py script each time instead of importing it.

I'm able to import the ku module, but I'm not sure how to use/pass it switches as ku.main() doesn't accept arguments...

I'm using a well known (Doge) wallet as an example:

> Passphrase: correct horse battery staple
> Public: DP5XzAYM55zzvtcLdZqG2JhszjHyNnvW8i
> WIF: QVD3x1RPiWPvyxbTsfxVwaYLyeBZrQvjhZ2aZJUsbuRgsEAGpNQ2
> WIF Unompressed: 6KdGAk9FD87ZAjW768vMc2FoffLAFpZZnSP7F7gPnyHUA9ttj7B

Importing the module and attempting to pass it arguments:
`import sys`
`from pycoin.scripts import ku`
`sys.argv = ['-u','-W','QVD3x1RPiWPvyxbTsfxVwaYLyeBZrQvjhZ2aZJUsbuRgsEAGpNQ2']`
`ku.main()`

Output:
> QVD3x1RPiWPvyxbTsfxVwaYLyeBZrQvjhZ2aZJUsbuRgsEAGpNQ2

So, the -u is appears to be completely ignored, same results if I change the -u to --uncompressed

Rearranging the -u to the end, appears that it completely ignores both switches and gives full output:
`sys.argv = ['-W','QVD3x1RPiWPvyxbTsfxVwaYLyeBZrQvjhZ2aZJUsbuRgsEAGpNQ2','-u']`
`ku.main()`

> input                         : QVD3x1RPiWPvyxbTsfxVwaYLyeBZrQvjhZ2aZJUsbuRgsEAGpNQ2
> network                       : Dogecoin mainnet
> netcode                       : DOGE
> secret exponent               : 88985120633792790105905686761572077713049967498756747774697023364147812997770
>  hex                          : c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a
> wif                           : QVD3x1RPiWPvyxbTsfxVwaYLyeBZrQvjhZ2aZJUsbuRgsEAGpNQ2
>  uncompressed                 : 6KdGAk9FD87ZAjW768vMc2FoffLAFpZZnSP7F7gPnyHUA9ttj7B
> public pair x                 : 54652445751364966014814199642702485207468864303823415690143529040235143060593
> public pair y                 : 72966369330535479126907188414667138321635397511721864437822996012971795952725
>  x as hex                     : 78d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71
>  y as hex                     : a1518063243acd4dfe96b66e3f2ec8013c8e072cd09b3834a19f81f659cc3455
> y parity                      : odd
> key pair as sec               : 0378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71
>  uncompressed                 : 0478d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71\
                                  a1518063243acd4dfe96b66e3f2ec8013c8e072cd09b3834a19f81f659cc3455
hash160                       : 79fbfc3f34e7745860d76137da68f362380c606c
 uncompressed                 : c4c5d791fcb4654a1ef5e03fe0ad3d9c598f9827
Dogecoin address              : DGG6AicS4Qg8Y3UFtcuwJqbuRZ3Q7WtYXv
Dogecoin address uncompressed : DP5XzAYM55zzvtcLdZqG2JhszjHyNnvW8i

---

It's possible that I'm going about this all wrong...
So, could you please let me know how to import ku and then use it without having to call/reload the actual ku.py script with command line switches every time?

**Comment by richardkiss** [comment]
Forget ```ku```, just use the Key class instead. It's much more direct.

    $ python
    >>> from pycoin.key import Key
    >>> k = Key.from_text("QVD3x1RPiWPvyxbTsfxVwaYLyeBZrQvjhZ2aZJUsbuRgsEAGpNQ2")
    >>> k.wif(use_uncompressed=True)
    u'6KdGAk9FD87ZAjW768vMc2FoffLAFpZZnSP7F7gPnyHUA9ttj7B'

**Comment by twig123** [comment]
Wow! That is 1000x faster! Thank you!!!!
