### ISSUE TITLE
tx --bitcoind-url and testnet

### ISSUE THREAD

**Issue by venzen** [richardkiss/pycoin#141]
Just to be sure, do I need to specify the environment variable `PYCOIN_SERVICE_PROVIDERS` in order to use the `--bitcoind-url` argument?

When I do, I'm still not sure that `tx` is using my local bitcoind testnet node. I run:

```
tx -n T --bitcoind-url http://bitcoinrpc:mypassword@10.8.0.1:18332 1e4215d92554720484b001562f9bdaaac2403a5bc770b80d88af8e4e10c1f6ff
```

and tx responds:

_tx: error: can't find Tx with id 1e4215d92554720484b001562f9bdaaac2403a5bc770b80d88af8e4e10c1f6ff_

So, I'm not sure why it won't work with that valid testnet txid. I have not defined `PYCOIN_CACHE_DIR` because I don't want cacheing.

BTW, where are the providers `BLOCKCHAIN_INFO`, etc defined?

**Comment by shayanb** [comment]
There are some issues with tx and testnet, not sure this would fall under those as you're using bitcoind.

as for providers, they are defined here: https://github.com/richardkiss/pycoin/tree/master/pycoin/services

**Comment by venzen** [comment]
Thanks for the feedback and link, @shayanb.

So, if I want to specify a local bitcoind node, is there a special variable to define in `PYCOIN_SERVICE_PROVIDERS` ?

Or do I just leave `PYCOIN_SERVICE_PROVIDERS` empty (or undefined) and then use `--bitcoind-url` ?

**Comment by shayanb** [comment]
you should not need anything related to service providers, but you might need a way to pass the netcode ( = 'XTN' ) somewhere.

Haven't tried pycoin with bitcoind so I really can't help you with that. let me know if you managed to make it work though :)

**Comment by venzen** [comment]
thanks, @shayanb , i ended up coding a solution for exploring txns on testnet using rpc.

**Comment by gustavklopp** [comment]
+1 for a testnet or regtest.

**Comment by richardkiss** [comment]
```PYCOIN_SERVICE_PROVIDERS``` has been deprecated in favor of ```PYCOIN_BTC_PROVIDERS``` or ```PYCOIN_XTN_PROVIDERS``` (etc.), so closing. You can use bitcoind now with ```PYCOIN_BTC_PROVIDERS=bitcoinrpc://user:passwd@hostname:8333```

**Comment by reiven** [comment]
@richardkiss this should be listed in the README, its very important to know how to set up local node.
