### ISSUE TITLE
Question: Can we update the version at PyPi?

### ISSUE THREAD

**Issue by BobbyBooShay** [richardkiss/pycoin#143]
I'm having a hard time getting 0.53 configured properly with my Python implementation unless I'm installing via "pip install pycoin". If I download pycoin-master and install via "pip install C:\pycoin-master" for some reason, the utilities such as "ku" no longer work and are throwing errors.

Be easy, I'm an amateur when it comes to Python and package management. I'm sure I am doing something wrong, just I did not see any clear instructions anywhere for how to properly handle this.

Thanks!

**Comment by shayanb** [comment]
Try this:
```
pip install https://github.com/richardkiss/pycoin/archive/master.zip
```
If you still see the errors, copy the errors here to see what seems to be wrong there.

**Comment by richardkiss** [comment]
Version 0.62 is now available.
