### ISSUE TITLE
example .py script for tx creation and broadcast?

### ISSUE THREAD

**Issue by derrend** [richardkiss/pycoin#144]
Hi,

I'm wanting a pure python script to create, sign and broadcast a transaction. COMMAND-LINE-TOOLS.md shows how to do it from the bash command line but if someone has a template of the python version I'd be grateful :)

so far...

    from pycoin.key.Key import Key
    x = Key.from_text('bip32address')

Not much, I know.
I'm also going to need to set

    PYCOIN_CACHE_DIR=~/.pycoin_cache
    PYCOIN_SERVICE_PROVIDERS=BLOCKR_IO:BLOCKCHAIN_INFO:BITEASY:BLOCKEXPLORER
    export PYCOIN_CACHE_DIR PYCOIN_SERVICE_PROVIDERS

will I do that from the command line or inside the python script?

Thanks :)

**Comment by XertroV** [comment]
@derrend, I don't have a template but I do have some code that does mostly what you're asking about: https://github.com/XertroV/nvbclient/blob/master/nvbclient/bitcoin.py

**Comment by derrend** [comment]
@XertroV Thanks very much for the help, if you do find yourself with five spare minutes and throw some example code my way I'd be grateful, still a bit of a coding novice I'm afraid :)

**Comment by XertroV** [comment]
@derrend I've written a little send-all-the-coins script to demonstrate the high level functions.

You should read the source code of each one once you're comfortable going deeper.

```
#!/usr/bin/env python3

import os
import argparse
from binascii import hexlify, unhexlify
import sys

from urllib.error import HTTPError

from pycoin.key import Key
from pycoin.tx.tx_utils import create_tx, sign_tx
from pycoin.services.blockchain_info import spendables_for_address, send_tx

parser = argparse.ArgumentParser()
parser.add_argument('--privkey-bytes', help='provide hexlified raw privkey bytes', default='', type=str)
parser.add_argument('--send-all-to', help='where to send all the money at this address', default='1MaxKayeQg4YhFkzFz4x6NDeeNv1bwKKVA', type=str)
args = parser.parse_args()

key_bytes = unhexlify(args.privkey_bytes.encode()) if args.privkey_bytes != '' else os.urandom(32)
private_key = Key(secret_exponent=int.from_bytes(key_bytes, 'big'))
address = private_key.address()

print('Your Bitcoin address is...', address)
print('Your --privkey-bytes', hexlify(key_bytes).decode())

try:
    spendables = spendables_for_address(address)
    print('Spending', spendables)
except HTTPError as e:
    print('Blockchain throws a 500 error if there are no spendables. Try sending some coins to', address, 'and try again. Remeber to copy privkey-bytes.')
    sys.exit()

tx = create_tx(spendables, [args.send_all_to])
print('TX created:', repr(tx))

sign_tx(tx, [private_key.wif(False), private_key.wif(True)])
print('Final TX:', tx)

print('TX Send Attempt:', send_tx(tx))
```

**Comment by derrend** [comment]
@XertroV Legend, thanks very much :)
