### ISSUE TITLE
Import transactions from openassets

### ISSUE THREAD

**Issue by lekanovic** [richardkiss/pycoin#154]
Hi,
I am trying to create colorcoins using the openassets protocol(https://github.com/OpenAssets/openassets.git) So the way I am doing that is I have a colorcore server running and I send my wallet bitcoin address to it. The colorcore server returns a raw transaction back containing one of the outputs as colored coin. 

So what I have been trying for a while now is to recreate that raw transaction in pycoin but I have ran into problems. 

**Raw transaction from ColorCore:**
0100000002b12711f432fb25b2cbbdce997d9177e2d2956df21888f6a22a79fb1da3532175020000001976a9145bacfcd3aa3bbcb43b7f9582e8560d91c391ebb588acffffffffb12711f432fb25b2cbbdce997d9177e2d2956df21888f6a22a79fb1da3532175030000001976a9145bacfcd3aa3bbcb43b7f9582e8560d91c391ebb588acffffffff0358020000000000001976a9145bacfcd3aa3bbcb43b7f9582e8560d91c391ebb588ac00000000000000001c6a1a4f410100010a13687474703a2f2f676f6f2e676c2f733334736430b2f953020000001976a9145bacfcd3aa3bbcb43b7f9582e8560d91c391ebb588ac00000000

**My bitcoin address that I have been using to create color coin**
mosh1uA8LcVqnRgj8XK1JFxrewj6hQ7YVG

**Code example:**
```
tx = Tx.tx_from_hex(tx_unsigned[1:-1]) 
print tx.as_hex(include_unspents=True) <----- this works fine I see the same transaction
tx.check_unspents()  <--- this one fails 'wrong number of unspents. Call unspents_from_db or set_unspents.'
```
So it seems that the unspents was not created and my next approach was to create the missing unspents by using the Spendable object. The problem that I am facing is that the Spendable object needs input from both the TxIn and TxOut. My question is how do I know which TxIn should correspond to TxOut? If someone can give some code examples that would be great.

Thanks!

**Comment by shayanb** [comment]
I have the same issue using bitcore or bitcoinJS to either make unsigned tx or partially sign the multisig transactions and try to sign it with pycoin.

**Comment by lekanovic** [comment]
I forgot to mention that colorcore is using python-bitcoinlib(https://github.com/petertodd/python-bitcoinlib) to create the unsigned transaction.
@shayanb do you mean that python-bitcoinlib is not supporting testnet?

**Comment by lekanovic** [comment]
I solve the problem and here is how I did it:

```
spendables = self.insight.spendables_for_address(bitcoin_address)

#tx_unsigned is the raw transaction that i get from colorcore server
tx = Tx.tx_from_hex(tx_unsigned[1:-1])
unspents = []
for txin in tx.txs_in:
    for s in spendables:
        if txin.previous_hash == s.tx_hash and txin.previous_index == s.tx_out_index:

            sp = Spendable(s.coin_value,
                            s.script,
                            txin.previous_hash,
                            txin.previous_index)
            unspents.append(sp)

tx.set_unspents(unspents)
```

**Comment by shayanb** [comment]
@lekanovic the testnet issue was just a guess, that turned out to be wrong ([multisig testnet support was just added])(https://github.com/richardkiss/pycoin/commit/6971a3bf78a06bad37e519d4434e05073a0fb312)

The issue I have is to use partially signed multisig transaction generated by bitcore or bitcoinjs and fully sign them with pycoin. I tried your solution for regular transactions and it works, have to try it with multisig.
