### ISSUE TITLE
Possible to spend from multiple addresses using create_signed_tx?

### ISSUE THREAD

**Issue by derrend** [richardkiss/pycoin#162]
If I wanted to create a transaction that spends inputs from more than one address could I do something like the following?:

    spendables = spendables_for_address(address1) + spendables_for_address(address2)
    signed_tx = create_signed_tx(spendables, payables, wifs=[address1wif, address2wif], fee="standard")

Can I pass in a list of spendables from two addresses and get a valid tx if I supply both of the necessary wifs?

Thanks

**Comment by richardkiss** [comment]
Yes, absolutely.

**Comment by derrend** [comment]
Great stuff, thanks very much :)

If you don't mind I also posted a question regarding multisig addresses at the bottom of this closed thread if you could please take a quick look?
https://github.com/richardkiss/pycoin/issues/95#issuecomment-158021405

Thanks again :)
