### ISSUE TITLE
Any way to override the URL of the services ? For example to use the testnet explorers 

### ISSUE THREAD

**Issue by skillachie** [richardkiss/pycoin#166]
For example with  the Blockr and other services. It would be nice to be able to specify or change the URL to be used with testnet without changing the code.

https://github.com/richardkiss/pycoin/blob/master/pycoin/services/blockr_io.py

**Comment by shayanb** [comment]
You either have to change the code or use other services that have the network-specific url in their code. e.g. https://github.com/richardkiss/pycoin/blob/master/pycoin/services/chain.py but too bad chain api is not active now.
I'm using blocktrail and blockcypher, if I get the time I'd add their support to pycoin

**Comment by skillachie** [comment]
Cool. No problem. I will update the code. Just wanted to be sure I was not doing what was already done.
I can also try to help out by starting support for blocktrail and blockcypher and you review ?

**Comment by shayanb** [comment]
@skillachie sure.

**Comment by richardkiss** [comment]
I'm working on changing how service providers work to better handle non-BTC-mainnet service providers and service providers that require authentication. You look at the work-in-progress at https://github.com/richardkiss/pycoin/tree/PYCOIN_PROVIDERS

**Comment by shayanb** [comment]
@richardkiss are you planning to change the file structure? I was planning to add blocktrail and blockcypher to the services

**Comment by richardkiss** [comment]
Testnet is now supported in with blockcypher, blockexplorer, blockr_io and chain_so providers.
