### ISSUE TITLE
chain.so previous_hash reversed

### ISSUE THREAD

**Issue by peter-conalgo** [richardkiss/pycoin#167]
Spendables created by `chain_so.ChainSoProvider.unspents_for_address` have the `previous_hash` in reverse byte order. Probably needs a `h2b_rev` in place of `h2b`.

Also, that class/method does not participate in `service_provider_methods()`

cc @dakk

**Comment by richardkiss** [comment]
Fixed in @ae8b705e01fd73dbaf7f2c9786418270f8db34d7
