### ISSUE TITLE
Biteasy scripts have a length prefix

### ISSUE THREAD

**Issue by peter-conalgo** [richardkiss/pycoin#168]
Spendable scripts created by `biteasy.spendables_for_address` seem to have a prefix byte equal to their length.

For example, I received:
`1976a9144ac8fa0dcb6036dae65d232f6b1ac729b4d817e288ac`
Instead of expected value:
`76a9144ac8fa0dcb6036dae65d232f6b1ac729b4d817e288ac`

0x19 == 25 == len(correct script)

**Comment by richardkiss** [comment]
I am dropping support for biteasy because it doesn't work very well for fetching transactions.
