### ISSUE TITLE
BIP70 Implementation

### ISSUE THREAD

**Issue by shayanb** [richardkiss/pycoin#174]
I'm researching on implementing BIP70, don't have any ideas how to start integrating it in pycoin yet, any ideas where to start? what would the best class structure be?

**Comment by richardkiss** [comment]
I've not investigated BIP70 much so I don't have anything to add at this point. Who is using it?

**Comment by shayanb** [comment]
Coinbase, Mycelium gear and most of the wallets such as Copay, Bitcoin core, Bitgo, Mycelium, Breadwallet, ... 
I think the lack of good server implementation is one of the reasons it's not out there yet.

**Comment by richardkiss** [comment]
This is a really complex protocol, and out of the scope for pycoin, so I'm closing this issue.
