### ISSUE TITLE
multisig addresses different from electrum

### ISSUE THREAD

**Issue by ulrichard** [richardkiss/pycoin#175]
I'm trying to check the balance of an electrum multisig wallet with pycoin.
The code is at  https://github.com/ulrichard/bitcoinutilities/blob/master/accounts.py  line 27 ff
But the generated addresses mostly don't match. The following two paths are about the only ones that I found matching:
m/0/0/0
m/0/0/3

**Comment by wizardofozzie** [comment]
Assuming you're talking about Electrum 2.x?
Also, it'd help to know the pubkey/address pairs which match (ideally with private keys and the root xprv and xpub, perhaps from a new seed, assuming that seed also has the issue

**Comment by ulrichard** [comment]
Using the three xpubs from https://github.com/ulrichard/bitcoinutilities/blob/master/accounts.json  
xpub6BjaGkAScEBXq35DypNEs5wZxW1ZQzKkmEjASbn4QWiUdaG8SQP51pYKuQbcRLdenZv8QqMGragaFbDVcqAt2uYBmoY77NcUK7HF9AX1dbS
xpub6CfJysMpnmzT9bzdbxZEbmGttGEuoeQRARe83c9hjPT871RcGQQVc8UzpBekt6yWiTHQM5GYiKXxu2Z41aFx2VWJczQCMHz2G8M4zYNYR6K
xpub6CSkaidzWnWjNGYifPYBsXQD7Pjgsawteq9yAkC44dzh51rWNYc3EKghG4RRTADhZYWuho7HN6K48e8eKJ9qyPnS7ipL9wU1czyFbaUe5zT
I created an electrum wallet. It generated the following addresses:

receiving
m/0/0/0 39vepiRE8btG3QfdHENnJzLDoGS2wYt8Se
m/0/0/1 3758USENfUN7srtNNrsP9JTKxDakRn7pms
m/0/0/2 3PzH7Yaw4hJ3eMPishNQnmFL1npWJJMqRv
m/0/0/3 3C7cSz1epidbMek6Vk13tUnVRnpnA27LKb
m/0/0/4 3GarRuiYgMYtx388CagqRHnUzcRoFSmjBJ
change
m/0/1/0 3DMCmsT5P4DM9qhnCEN5M88yeasbbMPYw8
m/0/1/1 3K9Z3Hik46BPnXDj5i98AjMYgKLVjAQnVr
m/0/1/2 32PkKU4DNKyX16vDybpprJ6ExPkJ69hLXw
m/0/1/3 3PhH47VE9RuDQr3KEzpx5BzsBNiDZvx5sr
m/0/1/4 381G5PUGVhS5T4jiePjWbQSkTNBFhDJKbK

Using my script from above with pycoin, it generates the following addresses:
receiving
0/0.pub 3HEzpGZkicZC6VrFyUoNNzCxPvfmLoVGwu
0/1.pub 35WHCrF71NEqNfnvLDZww2u1ukAAAiu4A7
0/2.pub 38EcoU1M4KHSxrWo9m3fd2VweuDFsmF2M5
0/3.pub 3Am8yHRxh6n6LdfLdoMfirdqvPhqPqwyEr
0/4.pub 3QcfD8yaBrx4etvkcseWDHjjD48uNjeJbp
change
1/0.pub 3BzTbrdHzNLuyZE6yBBSyR4ESfG4r3oJGC
1/1.pub 3Q3KfbvVgK53UtKsj5GktgmgUYc5C3tPht
1/2.pub 3Boeqhoi6q7YnQgAtAU9W7W25RPaFRk2vv
1/3.pub 3GjUiUoB4nTVE5AyP9rDxyRb2NfgsMPzC6
1/4.pub 381G5PUGVhS5T4jiePjWbQSkTNBFhDJKbK

**Comment by shayanb** [comment]
@ulrichard you should see how electrum sorts those addresses before making the multisig address. I had this issue with bitcore before, it's just the order of the pubkeys.

**Comment by ulrichard** [comment]
Yes, that fixes it. Thanks a lot.

**Comment by ROMANUCH05** [comment]
helping all cryptovaluta earning

**Comment by ROMANUCH05** [comment]
помоги вывести все биты !!!!не огорчу и тебя !)))))))))))
