### ISSUE TITLE
ECDSA signatures not low-s

### ISSUE THREAD

**Issue by instagibbs** [richardkiss/pycoin#178]
I see that the functionality was added: 

https://github.com/richardkiss/pycoin/commit/d65561428eae0da2807d583dc324652742212aee

Then moved elsewhere, so that signatures can now be high-s:  
https://github.com/richardkiss/pycoin/commit/185cb5ba1cb1126382bbda55d48bdbc7b72b48b0 

Was it intentional to allow the library to create high-s signatures? I don't really see much value, and it can result in random frustration(like in my case, esp since I thought it was enforced). 

Just curious.

**Comment by richardkiss** [comment]
Yes. Low-s is a bitcoin requirement, not an ECDSA requirement, so the ECDSA library shouldn't be enforcing it. (In fact, low-s is a red herring even for bitcoin, as it doesn't go that far to solving malleability.)

Sorry for your frustration. I've been there!

**Comment by instagibbs** [comment]
Fair enough, but libsecp enforces it normally, so interaction between the two gets a bit wonky. Thanks anyways.
