### ISSUE TITLE
Segregated Witness support

### ISSUE THREAD

**Issue by dakk** [richardkiss/pycoin#182]
Are there any plan / any dev planning to integrate segregated witness BIP inside pycoin?

**Comment by richardkiss** [comment]
Yes, I hope to support it, although there is no schedule yet.

**Comment by btcdrak** [comment]
The consensus code for BIP141 and BIP143 have been stable for some months now and implementations are close to deployment.

**Comment by richardkiss** [comment]
Work in progress in the segwit branch.

**Comment by richardkiss** [comment]
First crack of segwit done in 66e76e1ff6ed6e0693c6572916417e69a1f6f48a
