### ISSUE TITLE
Address version 76 signed?

### ISSUE THREAD

**Issue by shayanb** [richardkiss/pycoin#185]
How is this possible that pycoin made the transaction and signed it successfully for an output to this address `XeBSSWxXemnV23JRcaJtrPVxN7tbine29i` ?
on the wiki page [List of address prefixes](https://en.bitcoin.it/wiki/List_of_address_prefixes), the prefix of this address is listed under version 76 of 160 bit hashes. not sure if that means anything.

It translated to `14VbcGJdh4Zts6hqkgzfzrpAXnJugkW26L` when I checked the signed transaction hex.

on the other hand:

```
>>> from pycoin.encoding import is_valid_bitcoin_address
>>> print is_valid_bitcoin_address('XeBSSWxXemnV23JRcaJtrPVxN7tbine29i')
False
```

**Comment by richardkiss** [comment]
The code path take to parse the address just didn't bother validating the prefix. I don't know the transaction was created, so beyond that, I can't really say.

**Comment by shayanb** [comment]
Yes the transaction was created and almost was broadcasted too, however some sanity checks prevented that from happening as there was a mismatch in output requested and the output in the transaction hex. 
But i'm still not sure how that first address came into existence that end up a valid string for the whole code path, and if the ending address is actually related to the input text.
