### ISSUE TITLE
Feature Request: Pycoin Query/Transaction Support for DASH, tDASH Currency

### ISSUE THREAD

**Issue by cooperstevenson** [richardkiss/pycoin#187]
What areas of pycoin need to be modified/created to add transaction support in Pycoin?

**Comment by richardkiss** [comment]
If it's just a minor fork of bitcoin that uses the same script, transaction hashing, and signature algorithm, you can submit a patch to https://github.com/richardkiss/pycoin/blob/master/pycoin/networks.py.

**Comment by cooperstevenson** [comment]
Wow, you're fast! I'll take a look. P.S. I'm on the West coast...what are you doing up so late?!!?

**Comment by richardkiss** [comment]
Workin' on pycoin, of course. 😀  I'm in Pacific, so it's only 10:45 pm here.
