### ISSUE TITLE
"N of M" should be "M of N"

### ISSUE THREAD

**Issue by mflaxman** [richardkiss/pycoin#190]
Examples:
- https://github.com/richardkiss/pycoin/blob/4d9332621556eefa9bcc0a497b75e1744efaa702/tests/pay_to_test.py#L98-L124
- https://github.com/richardkiss/pycoin/blob/3e2583170c3632a0e3af3468b139ad37a5db9a2b/pycoin/tx/pay_to/ScriptMultisig.py#L22

Note: there could be _many_ more.

References:
- https://bitcoin.org/en/glossary/multisig
- https://en.wikipedia.org/wiki/Key_distribution

**Comment by richardkiss** [comment]
Fixed in 08b7c7d4d636f4e0689929e3d6806467fcc2ab8a
