### ISSUE TITLE
probs with logger: help please?

### ISSUE THREAD

**Issue by kumrzz** [richardkiss/pycoin#197]
hi guys, need some help please(sorry if this is a n00b issue!)
I get the following error when i call (after `from pycoin.tx.tx_utils import create_signed_tx`)
`create_signed_tx()`
> No handlers could be found for logger "pycoin.tx.script.vm"

so I added:
`import logging
logging.basicConfig()`
but then I stumble upon:

> ERROR:pycoin.tx.script.vm:script failed for unknown reason
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pycoin\tx\script\vm.py", line 172, in eval_script
    f(stack)
  File "c:\python27\lib\site-packages\pycoin\tx\script\microcode.py", line 195, in do_OP_DUP
    stack.append(stack[-1])
  File "c:\python27\lib\site-packages\pycoin\tx\script\vm.py", line 68, in __getitem__
    raise ScriptError("getitem out of range")
ScriptError: getitem out of range
ERROR:pycoin.tx.script.vm:script failed for unknown reason
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pycoin\tx\script\vm.py", line 172, in eval_script
    f(stack)
  File "c:\python27\lib\site-packages\pycoin\tx\script\microcode.py", line 195, in do_OP_DUP
    stack.append(stack[-1])
  File "c:\python27\lib\site-packages\pycoin\tx\script\vm.py", line 68, in __getitem__
    raise ScriptError("getitem out of range")
ScriptError: getitem out of range

should I make the config a bit more detailed[rather than `basicConfig()]`?
As you can see, I am on windows(10pro), but I have already set system environment variables:
`PYCOIN_CACHE_DIR:~/.pycoin_cache`
`PYCOIN_BTC_PROVIDERS:"blockr.io blockchain.info blockr.io blockexplorer.com"`

**Comment by richardkiss** [comment]
This is due to debug logging code that is produced when the script fails (the transaction is tested for validity so we don't destroy an already signed input). You can ignore it for now. I plan to remove these confusing messages soon.

**Comment by kumrzz** [comment]
hmm, meaning that in this case perhaps my tx failed a validity test(a signed input exists on the blockchain at that spendable point already)? Or that it wasn't able to connect to (any of) the provider(s) ? I mean you're saying we can ignore this debug logging code because it is a false warning, or something one should explore further for prudence?
thanks in advance Richard!

**Comment by richardkiss** [comment]
The messages appear even if the transaction is correctly signed (although it doesn't necessarily mean that it's been signed). You can ignore it. The ```create_signed_tx``` code does not do any network access.

**Comment by kumrzz** [comment]
gotit, thanks v much!
btw, I am calling pycoin.services.spendables_for_address() with netcode as the second argument, but the netcode seems to be getting ignored as I am getting nothing back for XTN, for instance. Is this code currently in flux(and I should clone later)? Should I be importing from another module ?

**Comment by richardkiss** [comment]
Not all service providers support testnet (in fact, few do). Take a look at the source of the service provider you're calling. Patches welcome!

**Comment by kumrzz** [comment]
yeah I was asking because I used tbtc.blockr.io successfully in a separate call(pycoin uses this as a provider and I have it switched on) ... sure, will take a better look later and submit a patch if poss ... thanks again Richard!
