### ISSUE TITLE
Why am I getting 'ValueError: insufficient inputs for outputs' even though my account has sufficcient credit?

### ISSUE THREAD

**Issue by derrend** [richardkiss/pycoin#199]
It's probably due to something I don't understand about the protocol but if anyone can shed some light on this for me I'd be grateful :)
version 0.62
```
>>> spendables = spendables_for_address('15ndvvRBPAtBwuXCgwPKSqJVsF45XPeLHy')
>>> spendables
[Spendable<19.2792 mbtc "b083554205db8f10b8600e1a335396274ee02955dfc99e27ed9b700ce984e880:4" 0/0/0>]
>>> x = create_signed_tx(spendables,[('1P337uJ4Z6fRr1n9XxJt1MmDR9oG8F77Zk', 1925905), '15ndvvRBPAtBwuXCgwPKSqJVsF45XPeLHy'], wifs=['ItsAsecret'],fee='standard')             
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pycoin/tx/tx_utils.py", line 203, in create_signed_tx
    tx = create_tx(spendables, payables, fee=fee, lock_time=lock_time, version=version)
  File "/usr/local/lib/python2.7/dist-packages/pycoin/tx/tx_utils.py", line 104, in create_tx
    distribute_from_split_pool(tx, fee)
  File "/usr/local/lib/python2.7/dist-packages/pycoin/tx/tx_utils.py", line 135, in distribute_from_split_pool
    raise ValueError("insufficient inputs for outputs")
ValueError: insufficient inputs for outputs
```

**Comment by derrend** [comment]
Just had a thought, could it be that I'm not leaving enough BTC unaccounted for to cover the transaction fee?

**Comment by shayanb** [comment]
you have an error here
```
>>> x = create_signed_tx(spendables,[('1P337uJ4Z6fRr1n9XxJt1MmDR9oG8F77Zk', 1925905), '15ndvvRBPAtBwuXCgwPKSqJVsF45XPeLHy'], wifs=['ItsAsecret'],fee='standard')             
```
where you are specifying the outputs (payables) you should either remove `15ndvvRBPAtBwuXCgwPKSqJVsF45XPeLHy` or add an amount for it like your first output.

**Comment by derrend** [comment]
Sorry I should have mentioned I'm still on version 0.62, I'm under the impression that if I don't specify an amount for my second input then any remaining amount (minus the tx fee) would be sent there.

I take advantage of this because the tx fee varies depending on the size of the transaction (in bytes).
Has this behaviour changed in v0.7?

**Comment by shayanb** [comment]
I see, I never used that method as it didn't make sense to me how this is working: https://github.com/richardkiss/pycoin/blob/master/pycoin/tx/tx_utils.py#L106

usually I build the logic myself to calculate and add change address/amount as the second output.

**Comment by derrend** [comment]
Your method sounds more robust. I will consider implementing the same practice :)

**Comment by richardkiss** [comment]
Ultimately, I'd like to get create_tx to be THE best and easiest way to new transactions, so I do appreciate input on how to massage it to make it more useful.

**Comment by derrend** [comment]
Mr Kiss, bit off topic but please could you add support for [zcoin](https://github.com/zcoinofficial/zcoin) to your pycoin library?

I've got an app or two in mind but no way to build them as yet.
I'll happily pay you for your efforts, let me know how much you want and I'll send the funds to your btc donation address (so long as it's not too enormous :wink:).

If you feel like outlining the steps to add support for coins so I can add my own in future I might find that really useful too :grin:

Let me know if you're up for it :smile:

**Comment by richardkiss** [comment]
I'm no zcoin expert, but my guess is that the changes required to pycoin would be pretty significant.

**Comment by derrend** [comment]
Ah I see, may not be worth it then but thank you any way, I was basically looking for a deterministic key generation quick fix.

**Comment by richardkiss** [comment]
The ```ku``` tool may work with zcash addresses, possibly even BIP32-style... maybe you could give it a try? You might have to use the master branch.

**Comment by derrend** [comment]
Thanks for the suggestion but Zcash functionality is not what I'm looking for Zcoin is what I'm interested in ;)

**Comment by richardkiss** [comment]
Sorry, I can't keep my alt-coins straight! It's fairly straightforward to get keys working on new alt-coins if they're not too different from bitcoin... take a look at https://github.com/richardkiss/pycoin/blob/master/pycoin/networks/legacy_networks.py for examples.

**Comment by derrend** [comment]
I took a look at that file initially but I couldn't (and still don't) understand how to discover the paramiters I would need to incorporate Zcoin.
For example with Litecoin where do all these values come form?
>b'\xb0', b'\x30', b'\5', h2b('019d9cfe'), h2b('019da462'))

The reason I'm trying to work this out is because community politics is forcing Zcoin to fork next week but it can take days to sync a node. Many community members don't have the expertise or resources to set one up so they can't get their money out of the exchanges. If I can work out how to add Zcoin to your pycoin library they will have a way to withdraw their coins.

**Comment by richardkiss** [comment]
Most of these numbers are prefixes for the various key types (P2SH, P2PKH, BIP32 public and private keys), and they're arbitrary values determined by the coin creators. You should look at the reference implementation. What letter do addresses start with in Zcoin? Take a look at https://en.bitcoin.it/wiki/List_of_address_prefixes

**Comment by derrend** [comment]
Ah I see. The addresses start with an 'a'.
Thank you for the link I will start familiarising myself.

Also thanks again for the help sir :)
