### ISSUE TITLE
tx script -h option does not work

### ISSUE THREAD

**Issue by yevhen-m** [richardkiss/pycoin#201]
```
$ tx -h
Error: Not a valid JSON!
```
```
python 3.5.1
pycoin==0.70
```

**Comment by richardkiss** [comment]
Can't reproduce, can you do ```which tx```? I think you're running some tool unrelated to pycoin.

**Comment by yevhen-m** [comment]
@richardkiss thanx, you are right, `tx` is mapped to another function.
