### ISSUE TITLE
Dealing with Nulldata - current issues

### ISSUE THREAD

**Issue by XertroV** [richardkiss/pycoin#203]
Currently pycoin does deal with nulldata to some degree (I submitted the original PR), but there are a few problems:
1. Nulldata over 40 bytes is not matched agains the nulldata template ([ref](https://github.com/richardkiss/pycoin/blob/master/pycoin/tx/pay_to/ScriptType.py#L72)), however, nulldata up to 80 bytes is considered standard (as of bitcoin core 0.12 IIRC)
2. Even though nulldata txs over 40 or 80 bytes are non-standard, they are still nulldata outputs
3. Some nulldata is improperly formatted ([example](https://www.blocktrail.com/BTC/tx/82da9ffc424ccd20b8f9ba47e7f5c3bf661e1b3a0e6bfda76296df8921e63a2b#tx_messages)), even though it decodes to something somewhat meaningful (though it's hard to tell how much of the non-ascii bytes are meaningful)

I noticed this because 3) was throwing errors in my [nulldata-api-thing](http://opreturn.ninja/#main). Called via `pycoin.tx.pay_to.__init__.script_obj_from_script`, the error is `unexpected end of data when literal expected, <class 'pycoin.tx.script.ScriptError'>`. The relevant traceback is included below. Particularly the error is in the lines:

`opcode1, data1, pc1 = tools.get_opcode(script, pc1)`

`raise ScriptError("unexpected end of data when literal expected")`
## Suggested Solutions

For 1), the obvious solution is to bump the length parameter to 80 bytes instead of 40.

For 2), I think we should actually drop the length check all together. Two possible things could happen (AFAIK). The first is that we have a well-encoded nulldata entry (regardless of length) and the second is that we have a badly encoded entry as in 3). Badly encoded entries should be dealt with separately I feel. Additionally I think we should probably accept _any_ well encoded nulldata txout, regardless of whether it's standard or not. This is also rather more future compatible.

For 3), I don't think we should deal with this in the ScriptNulldata class and template. It would require extensive changes to the script parser because it currently expects nulldata and other variable length data to be length encoded. Rather, we _could_ create another script type called ScriptRawNulldata or something, which is very similar to ScriptNulldata, but just dumps back _everything_ after the OP_RETURN. I don't know how well this would fly with the template matching engine, or if it's possible.

Part of me wants to argue that they aren't actually Nulldata outputs at all; since nulldatas are by definition length encoded [citation needed]. Rather, they're just provably prunable outputs.

Additionally, bitcoind doesn't decode them, it just returns: `"asm": "OP_RETURN [error]",`.
#### Maybe a better way to deal with 3)

A second way to deal with 3) would be to catch the ScriptError in ScriptNulldata and set the nulldata to `[error]` - the output would then match bitcoind and the hex is available in the script anyway, so it's still accessible.
## What I'm going to do

I'm going to create and submit a PR to fix 1 and 2 by removing the length check. Since (I think) the template matching engine will pick up any valid length encoded nulldata this should have no side effects besides some nulldatas being parsable when they weren't previously.
#### Traceback from point 3)

```
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:   File "/home/bitcoin/src/opreturn-ninja/opreturnninja/models.py", line 91, in merge_nulldatas_from_block_obj                           Oct 12 00:22:04 bitcoin-node-2 bash[22792]:     script_object = script_obj_from_script(tx_out.script)                                                                               Oct 12 00:22:04 bitcoin-node-2 bash[22792]:   File "/home/bitcoin/.venv/opreturn/lib/python3.5/site-packages/pycoin/tx/pay_to/__init__.py", line 34, in script_obj_from_script
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:     st = sc.from_script(script)
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:   File "/home/bitcoin/.venv/opreturn/lib/python3.5/site-packages/pycoin/tx/pay_to/ScriptNulldata.py", line 17, in from_script
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:     r = cls.match(script)
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:   File "/home/bitcoin/.venv/opreturn/lib/python3.5/site-packages/pycoin/tx/pay_to/ScriptType.py", line 60, in match
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:     opcode1, data1, pc1 = tools.get_opcode(script, pc1)
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:   File "/home/bitcoin/.venv/opreturn/lib/python3.5/site-packages/pycoin/tx/script/tools.py", line 63, in get_opcode
Oct 12 00:22:04 bitcoin-node-2 bash[22792]:     raise ScriptError("unexpected end of data when literal expected")
```

**Comment by richardkiss** [comment]
Sounds pretty reasonable to me!
