### ISSUE TITLE
Is it possible to sign an unsigned transaction with pycoin? (hex format)

### ISSUE THREAD

**Issue by derrend** [richardkiss/pycoin#206]
I have the unsigned raw tx already from a third party, I just need to sign it:

```
tx = '01000000017b1eabe0209b1fe794124575ef807057c77ada2138ae4fa8d6c4de......"
signed_tx = sign_tx(tx, wifs=[source_wif], netcode='BTC')
```

I believe this is wrong because I'm getting a `"'unicode' object has no attribute 'sign'"` error.
If someone can point me in the right direction I'd appreciate it :)

**Comment by richardkiss** [comment]
Your transaction must be a Tx instance, not hex. Try

```
tx = Tx.from_hex('01000000017b1eabe0209b1fe794124575ef807057c77ada2138ae4fa8d6c4de...')
sign_tx(tx, wifs=[source_wif])
```

**Comment by derrend** [comment]
Thank you for the advice :)
I have a new error now though:
```
>>> signed_tx = sign_tx(tx, wifs=[source_wif])               
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pycoin/tx/tx_utils.py", line 172, in sign_tx
    tx.sign(LazySecretExponentDB(wifs, secret_exponent_db), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoin/tx/Tx.py", line 433, in sign
    self.check_unspents()
  File "/usr/local/lib/python2.7/dist-packages/pycoin/tx/Tx.py", line 388, in check_unspents
    raise ValueError("wrong number of unspents. Call unspents_from_db or set_unspents.")
ValueError: wrong number of unspents. Call unspents_from_db or set_unspents.
```
Just FYI this is a counterparty transaction in case that is important.

**Comment by richardkiss** [comment]
You need to call "set_unspents" with the unspents you are spending. The Tx hex you're including doesn't seem to have them. You can fetch them using services. I know, this is a mess and a bit confusing, but it's how bitcoin works.

**Comment by richardkiss** [comment]
Did you come to a resolution on this?

**Comment by derrend** [comment]
I did thanks, followed your advice and it worked great. Closing.
