### ISSUE TITLE
A means to override user-agent?

### ISSUE THREAD

**Issue by peter-conalgo** [richardkiss/pycoin#219]
It seems some Insight providers are blocking API requests by looking at the user-agent. For example, a request like this to `localbitcoinschain.com`:

```
curl -A Python-urllib/3.5 https://www.localbitcoinschain.com/api/addr/1PBDnk9JdQ4ckwyM5RPMsULegYo8C8W7k4/utxo
```
... will fail with 403 from Cloudflare, but ...

```
curl -A whatever https://www.localbitcoinhain.com/api/addr/1PBDnk9JdQ4ckwyM5RPMsULegYo8C8W7k4/utxo
```

... works fine.

IMHO, it would be appropriate to put "pycoin/0.71" as the user agent for the requests coming from this library. However, if that's done, then it should be done for all the different providers.

**Comment by richardkiss** [comment]
Done in ee8c5c1fe858ef28063f3095263b096c43fef88e
