### ISSUE TITLE
Time for a new release version?

### ISSUE THREAD

**Issue by peter-conalgo** [richardkiss/pycoin#220]
Lots of good stuff got into the library recently, and it would really help me if you made a formal release (ie. `0.80`).

We use `pycoin` in [Opendime](https://Opendime.com) and it bakes-in a URL to the release on Github so that it can execute on any python stack without install steps. That baking process is set to happen over the next week or so.

**Comment by richardkiss** [comment]
I've release 0.75 from the master branch onto pypi. Hope this helps!

**Comment by peter-conalgo** [comment]
Thanks! It does help me.
