### ISSUE TITLE
Module encoding valid address not work well

### ISSUE THREAD

**Issue by YaaMe** [richardkiss/pycoin#234]
`allowable_prefixes` not access to `bitcoin_address_to_hash160_sec_with_prefix`?

https://github.com/richardkiss/pycoin/blob/master/pycoin/encoding.py#L301

you can test the [address](https://insight.bitpay.com/address/3KzbJxZVrFWuhCmf8t7fW87yiWVd3qQWqT)
> 3KzbJxZVrFWuhCmf8t7fW87yiWVd3qQWqT

and you will get False
Is it BUG?

**Comment by richardkiss** [comment]
The function you want is in https://github.com/richardkiss/pycoin/blob/master/pycoin/key/validate.py

And it will move to ```pycoin.ui``` soon.
