### ISSUE TITLE
Bitcoin address to Hash160

### ISSUE THREAD

**Issue by Napulsnik** [richardkiss/pycoin#238]
Hello. How can I get Hash160 (only) from Bitcoin address? I have txt file whith addresses.
Example:
cat addresses.txt | ku | grep hash160 > result.txt - Not working
ku addresses.txt | grep hash160 > result.txt - can't parse

**Comment by richardkiss** [comment]
Try

cat address | xargs -n1| ku | grep hash160

**Comment by Napulsnik** [comment]
Hi.
$ cat addr.txt | xargs -n1 | ku | grep hash160 > hash160.txt
usage: ku [-h] [-w] [-W] [-a] [-u] [-P] [-j] [-s SUBKEY]
          [-n {BTC,XTN,LTC,XLT,VIA,TVI,FTC,FTX,DOGE,XDT,BC,DASH,tDASH,MEC,MYR,UNO,JBS,MZC,RIC,DFC,FAI,ARG,ZEC,BTCD}]
          [--override-network {BTC,XTN,LTC,XLT,VIA,TVI,FTC,FTX,DOGE,XDT,BC,DASH,tDASH,MEC,MYR,UNO,JBS,MZC,RIC,DFC,FAI,ARG,ZEC,BTCD}]
          item [item ...]
ku: error: too few arguments
xargs: echo: terminated by signal 13

**Comment by richardkiss** [comment]
Sorry, no "|" between xargs and ku.

```cat addr.txt | xargs -n1 ku | grep hash160```

You can also use -j in ku to create json output, and then parse it with a command-line json processor like https://stedolan.github.io/jq/

**Comment by richardkiss** [comment]
Did you get this working? Can I close this issue?

**Comment by Napulsnik** [comment]
Yes, thank you!

**Comment by agoora** [comment]
Command  "cat addr.txt | xargs -n1 ku | grep hash160"  give me this message :+1: 

can't parse 3A1Rp7pkcETkukPjLBvW3AUYwfrokZEfuQ
can't parse 3Po6LdjDSVRwsGJYA6avhvo82fTzxjFmA7

Where is the problem ?
