### ISSUE TITLE
Bech32 & segwit address support?

### ISSUE THREAD

**Issue by afk11** [richardkiss/pycoin#242]
I've been reviewing for common libraries that may not yet have segwit address support. I haven't seen anyone work on it yet, please add this soon!

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

**Comment by richardkiss** [comment]
The ```ku``` tool supports this in the master branch. Check https://github.com/richardkiss/pycoin/blob/master/tests/cmds/test_cases/ku/bip32_xprv.txt for an example. (This is a test case, in fact.) Look at the last few lines of this file.
