### ISSUE TITLE
Does pycoin have support for P2SH SegWit addresses?

### ISSUE THREAD

**Issue by metamarcdw** [richardkiss/pycoin#244]
I see there is support for native SegWit addresses with bech32, but I can't find a clear way to generate and use P2SH SegWit addresses.

**Comment by sowbug** [comment]
If you mean P2SH(P2WPKH), you can do it like this:
```
from pycoin.key.BIP32Node import BIP32Node
from pycoin.tx.pay_to.ScriptPayToAddressWit import ScriptPayToAddressWit
from pycoin.ui import address_for_pay_to_script

# https://github.com/trezor/python-mnemonic/blob/master/vectors.json
XPRV = "xprv9s21ZrQH143K3h3fDYiay8mocZ3afhfULfb5GX8kCBdno77K4HiA15Tg23wpbeF1pLfs1c5SPmYHrEpTuuRhxMwvKDwqdKiGJS9XFKzUsAF"

node = BIP32Node.from_wallet_key(XPRV)
key = node.subkey_for_path("49'/0'/0'/0/0")
hash160_c = key.hash160(use_uncompressed=False)
p2aw_script = ScriptPayToAddressWit(b'\0', hash160_c)

# Should print 3Aho3kS7vgVWKTpRHjcqBoPXiCujiSuTaZ
# Confirm at https://iancoleman.github.io/bip39/
print address_for_pay_to_script(p2aw_script.script())
```

I figured this out by looking at pycoin's test code and guessing at the rest. Richard, if you're reading this, it would be awesome to build this into the `ku` utility, as I haven't yet encountered the `p2` form of SegWit addresses in the wild.

**Comment by sowbug** [comment]
Well, what do you know. as I was preparing a pull request to add it into `ku`, I noticed https://github.com/richardkiss/pycoin/commit/a4f910749f0d5e25e21ef0a0f8dae18a07b00bcf which already does it!

@metamarcdw take a look at that commit, and it'll show how to do it correctly as of 19 days ago. Mine wasn't too far from correct, except I missed the key._netcode optional argument, which probably happened to work for the main Bitcoin chain.

I am guessing Richard will close this issue as already implemented, but waiting for a new release.

**Comment by metamarcdw** [comment]
Thanks for that sowbug, that was a great help.
