### ISSUE TITLE
TypeError: urlopen() got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by alt473** [richardkiss/pycoin#248]
Hello, when I try to:

`broadcast_tx(tx)`

I have an error:

`File "/home/dev/environments/pycoin/lib/python3.5/site
packages/pycoin/services/blockchain_info.py", line 60, in broadcast_tx
    d = urlopen(URL, data=data).read()
TypeError: urlopen() got an unexpected keyword argument 'data'
`

what wrong with this?

Thanks

**Comment by richardkiss** [comment]
Give this a try.
