### ISSUE TITLE
Master branch is much slower than 0.8 release

### ISSUE THREAD

**Issue by shivaenigma** [richardkiss/pycoin#254]
- The speed branch improvements seems not to be working on master
- 0.8 is much much faster, key generation is very slow now
- I am still using PYCOIN_NATIVE=openssl (no changes in that)

**Comment by richardkiss** [comment]
Point multiplication was not using OpenSSL in `develop`, and it may affect `master` too. I've fixed it in `develop` in d06aefaefac609fc26527aca27ac5486a6ba011c.

It may be not too difficult to backport to master or to 0.8. Let me take a look.

**Comment by richardkiss** [comment]
Okay, efd20ad62dc66168bfa25502cbbc426d573f8acb should resolve this.
