### ISSUE TITLE
How to create new Key from random secret exponent?

### ISSUE THREAD

**Issue by lorien** [richardkiss/pycoin#264]
Can the pycoin lib generate secret exponent for me?

**Comment by metamarcdw** [comment]
You could use the PyCrypto RNG:

```
from Crypto.Random import random
from pycoin.key import Key

se = random.getrandbits(256)
key = Key(secret_exponent=se)

key.address()
```

**Comment by lorien** [comment]
My concern is code from another library: https://github.com/blockstack/pybitcoin/blob/master/pybitcoin/privatekey.py#L26
It also generates 256 bits (32 bytes from /dev/random) and then compare it with curve order (whatever it is). The curve order is the `_r` variable in your code https://github.com/richardkiss/pycoin/blob/master/pycoin/ecdsa/secp256k1.py#L12

So, the question is should I check that getrandbits(256) is less then `_r`? I have no idea whtat does this mean but it was implemented in another library for some reason.

**Comment by richardkiss** [comment]
The private keys k and k+_r produce the same address and signatures. If it's larger than _r, you can leave it alone, you can subtract _r, or you can try the random process again. In practice, if you get something larger than _r, it's more likely a bug.

**Comment by lorien** [comment]
```
Do I understand correctly that maximal number that could be returned from `getrandbits(256)` is `2**256 - 1`?

This code fails:
```
from pycoin.key import Key
from Crypto.Random import random


#sec = random.getrandbits(256)
sec = 2**256 - 1
key = Key(secret_exponent=sec)
```
with error
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    key = Key(secret_exponent=sec)
  File "/home/lorien/web/ufobet/.env/lib/python3.5/site-packages/pycoin/key/Key.py", line 70, in __init__
    raise InvalidSecretExponentError()
pycoin.key.Key.InvalidSecretExponentError
```

**Comment by richardkiss** [comment]
Ah yes, you're right, the Key class doesn't like secret exponents larger than _r, the order of the group. If the secret exponent you get is larger, you'll have to try again (or subtract _r).

**Comment by richardkiss** [comment]
For entropy, try os.urandom (which I believe gets bytes from /dev/urandom).
