### ISSUE TITLE
Any way to determine if address is Segwit or not?

### ISSUE THREAD

**Issue by loper** [richardkiss/pycoin#269]
Simple check by first char - "1" or "3" would be not good, because of multisig. By segwit address I mean this one of address_for_pay_to_script (like '3QEhaqr...'). Is there any simple way to determine, what function to use (ScriptPayTo...) by only address or hash160 given?

**Comment by loper** [comment]
For bech32 it's nicely shown:
```
netcode_and_type_for_text('bc1qlcggctgcy5myp7xpa8u3h0uvhc2ukk8xyeemaq')
Out[5]: ('BTC',
 'segwit', (...)
```

**Comment by richardkiss** [comment]
If the address starts with a 3, it's a pay-to-script-hash. It might correspond to a segwit script or it might not. There is no way to know until you find the pay-to-script that has the given hash.
