### ISSUE TITLE
p2sh_segwit form Key.py

### ISSUE THREAD

**Issue by axelxod** [richardkiss/pycoin#300]
hi i use
from pycoin.key import Key
def secret_to_address(secret_exponent):
    k = Key(secret_exponent=secret_exponent)
    addr = k.address(use_uncompressed=True)
    caddr = k.address()
    wif = k.wif(use_uncompressed=True)
    return secret_exponent, wif, addr, caddr
and i can get btc address. but how i can get segwit address?

**Comment by loper** [comment]
From ku.py:

> from pycoin.tx.pay_to.ScriptPayToAddressWit import ScriptPayToAddressWit
> from pycoin.ui import address_for_pay_to_script
> 
> p2aw = ScriptPayToAddressWit(b'\0', k.hash160())
> Out[496]: <Script: pay to bc1qlcggctgcy5myp7xpa8u3h0uvhc2ukk8xyeemaq (segwit)>
> 
> p2aw.address()
> Out[497]: 'bc1qlcggctgcy5myp7xpa8u3h0uvhc2ukk8xyeemaq'
> 
> address_for_pay_to_script(p2aw.script())
> Out[498]: '3D4Az6kBnjcWVqNtbTZdKKZJiBBR9DQ9Te'
