### ISSUE TITLE
Deriving BTC Addresses from my HD wallet's xPub 

### ISSUE THREAD

**Issue by mszczech01** [richardkiss/pycoin#304]
Hello everyone,

I've been struggling all day trying to generate my HD wallets BTC addresses using my xPub. I've tried many different tools and have not had success. Can someone explain the usage of the command line tool for this application.

I have been attempting this using the following command:
`Ku -a P:[my x pub] -s 0/0-10 -a`

With this command, I received an output of 10 addresses but these addresses are not associated with this wallet.

Please let me know the proper commands to retrieve the addresses associated with this account. If the addresses are not yet determined, please let me know how I can generate these addresses using my wallets xPub.

**Comment by richardkiss** [comment]
Try it without the two characters P:

**Comment by richardkiss** [comment]
Take a look at https://github.com/richardkiss/pycoin/blob/master/COMMAND-LINE-TOOLS.md for some examples.

**Comment by mszczech01** [comment]
thanks for responding @richardkiss ! I tried to use it without using the P character and used:
`ku [xPub] -s 0/0-10 -a`

but I still haven't had any results that reflect the addresses on my wallet.

**Comment by mszczech01** [comment]
I have been looking at the tool documentation and have been a bit confused to be honest. 

I am using a trezor and I have generated the xpub using the path "49'/0'/0'" as instructed in the trezor documentation. To my understanding, the first address under this account should be identical to the first address I derive using the xPub.

**Comment by mszczech01** [comment]
when testing the ku command, I had noticed that my child index is appearing as: 0H (2147483648). Maybe these addresses are valid but they are being displayed in reverse order?

**Comment by richardkiss** [comment]
`0H` is the canonical way of writing `0'`. They are the same.

A hardened address sets the bit `0x80000000` = 2147483648 (and uses a different algorithm that has the private key as input to generate the child).

**Comment by richardkiss** [comment]
I'm going to close this issue for now. Feel free to re-open with more info if you'd like more help.
