### ISSUE TITLE
Where did Key.from_text() go?

### ISSUE THREAD

**Issue by kousu** [richardkiss/pycoin#316]
The [current docs](https://github.com/richardkiss/pycoin/blob/171a9cd9b0b06ea298062942fe19802a5da61990/README.md#pycoinkeykey) claim 
> Key.from_text(b58_text) accepts an address (bitcoin or other), a WIF, or a BIP32 wallet string and yield a Key.

but the [current version](https://github.com/richardkiss/pycoin/blob/171a9cd9b0b06ea298062942fe19802a5da61990/pycoin/key/Key.py#L83) only has `from_sec()`.

I see that [the tests](https://github.com/richardkiss/pycoin/blob/171a9cd9b0b06ea298062942fe19802a5da61990/tests/keyparser_test.py) use `ui.key_from_text.key_from_text()`. Is that the new place? Is it an oversight that the old API died? Could you shim in the old API or are you going to update the docs?

Thank you for pycoin. It really helps to elucidate the specs to be able to see some working code.

**Comment by richardkiss** [comment]
I'm moving all API to under each coin's network. Parsing an address will be done with `network.parse.address`; parsing a WIF will be done with `network.parse.wif`. To get a network, `from pycoin.symbols.btc import network`. This will eventually be v0.9.

**Comment by kousu** [comment]
Thank you, I've been writing `from pycoin.symbols.btc import network; network.ui.parse()` for the last couple days and it has been helpful to know that that is the sanctioned way going forward. Cheers!
