### ISSUE TITLE
can not find subkey btc in xpub (blockchain.com)

### ISSUE THREAD

**Issue by ttrasn** [richardkiss/pycoin#322]
Hi,
I used [blockchain.com ](blockchain.com)xpub
then I used this code to create subkeys,
`#!/usr/bin/python
from pycoin.key import Key
import sys

sub1 = int(sys.argv[1])
sub2 = int(sys.argv[2])

key = Key.from_text(
        'xpub.....').subkey(
        sub1). \
        subkey(sub2)
address = key.address()
print(address)`

and send this address to freands for send BTC to this address.
when they send me BTC, I see transaction is confirmed but not comming in my blockchain.com wallet!
where is my mistake ?

**Comment by richardkiss** [comment]
There are a lot of subkeys under any given BIP32 node. Wallet software can only consider addresses under a few of them, and blockchain.com's wallet is not looking at the address that your coins have been sent to. I don't know much about their wallet, but you need some way to tell it to look at the address at the path you generated. Alternatively, maybe you can get the xprv and use other tools (like pycoin's tx tool) to generate and sign a transaction. Let me know if you think I can help further.

**Comment by richardkiss** [comment]
I'm going to close this. Feel free to re-open if you think I can further help you.
