### ISSUE TITLE
Last release from 2017?

### ISSUE THREAD

**Issue by reiven** [richardkiss/pycoin#331]
Hi, i'm checking the code, and since the last release (0.80, on sep 2017) there was some changes, probably it will be a good idea create a new release?

Thanks

**Comment by richardkiss** [comment]
I agree. I've been doing a lot of refactoring, and things aren't perfect yet, and that's made me leery of creating a new release. But I should do so soon even though things aren't perfect.

**Comment by richardkiss** [comment]
New release 0.90.20190630 now available.
