### ISSUE TITLE
pycoin.ui.key_from_text removed

### ISSUE THREAD

**Issue by davidmak2709** [richardkiss/pycoin#344]
Since the `pycoin.ui.key_from_text` was removed, is there any other function to get the same result?

**Comment by richardkiss** [comment]
First you get the network

`from pycoin.symbols.btc import network`

See also https://pycoin.readthedocs.io/en/latest/api.html#networks

Then you parse. Take a look at https://pycoin.readthedocs.io/en/latest/api.html#network-parse

`contract = network.parse.address(address)`

It seems the `Contract` is not in the documentation but the API is here: https://github.com/richardkiss/pycoin/blob/master/pycoin/networks/Contract.py

**Comment by richardkiss** [comment]
Now documented at https://pycoin.readthedocs.io/en/0.90.20190728/source/contract.html

**Comment by davidmak2709** [comment]
Ok, but I'm using Dash and a BIP32 to generate the keys. So instead my import will be:

`from pycoin.symbols.dash import network`

Then I parse the BIP32 with:

`bip = network.parse.bip32(MY_BIP32)`

Now the generation of the public key works just fine, but I'm struggling with the WIF. I think that's because the `bip` object doesn't have the secret exponent.  How to add it or generate it?
