### ISSUE TITLE
Equivalent of `netcode_and_type_for_text` in 0.90

### ISSUE THREAD

**Issue by datgrog** [richardkiss/pycoin#350]
Is there anything like `netcode_and_type_for_text` in the latest release ? 
It was convenient for parsing and checking input type + network easily 😄

**Comment by datgrog** [comment]
I investigate a bit and what come close to `netcode_and_type_for_text` is `parse_key` under pycoin.cmds.ku. It does not return what hardcoded types `["hierarchical_key", "private_key", "public_key", "address"]` it used to infer the input in case it works but it's fine for me anyway.

- My suggestion (below workaround) is to move BTC testnet first or second to not recognised a `tpub...` ext pub key as a Feathercoin's one.

```
XTN_network_idx = [network.symbol for network in parse_networks].index('XTN')
parse_networks.insert(0, parse_networks.pop(XTN_network_idx))
```

**Comment by richardkiss** [comment]
And you've just described the problem with the API as it originally existed, and why it was removed. A given string might have multiple interpretations for given networks (and now that the parsing can be made arbitrarily general for each network, there is no guarantee they will even return the same type!). So if this kind of function were to return, it would have to return an iterator (or list) of possible interpretations.

Your workaround may be useful for you, but for people who use exclusively Feathercoin, it would be a problem.

Happy to discuss further.

**Comment by datgrog** [comment]
Thanks for your detailed answer, sounds good.

**Comment by robinsingh-bw** [comment]
> Thanks for your detailed answer, sounds good.

Hey, are you interested in some freelance work? Need help with an old issue that you worked on related to ypub keys on bitcore. Email me on robin@koinly.io
