### ISSUE TITLE
Support creation of HD wallet and store in bitcoin Core folder

### ISSUE THREAD

**Issue by ravikant2986** [richardkiss/pycoin#351]
I am trying to connect to the local (bitcoin core) through rpc. I have setup environment variables using export PYCOIN_XTN_PROVIDERS=bitcoinrpc://user:password@host:18332.
But when I create a wallet it doesn't show in my bitcoin Core wallet folder(bitcoin-cli listwalletdir)

can you please confirm if it is possible to create HD wallet in my bitcoin Core wallet folder like 
bitcoin-cli createwallet "wallet_name" so I can use all bitcoin core function with this wallet.

**Comment by ravikant2986** [comment]
Hi @richardkiss thanks for reply, let me try to explain what I want to achieve. I have installed bitcoin core on my server and trying to create HD wallet there using pycoin. So my concern is where does pycoin store wallet, is it possible to create wallet on my bitcoin core like bitcoin-cli createwallet does.

In short I want to create HD wallet on my server like bitcoin-cli createwallet does.

**Comment by richardkiss** [comment]
I'm not familiar with the format of the bitcoin core wallet. My guess is this would require writing at least some code, possibly a fair amount. Note that pycoin does not store a wallet anywhere. You can create a key with `ku`, but it gets displayed to the console and that's the end of that; it's not stored anywhere.
