### ISSUE TITLE
tx command gives different result than readme

### ISSUE THREAD

**Issue by blutooth** [richardkiss/pycoin#356]
When I execute the command:
tx -i 12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX
a3a6f902a51a2cbebede144e48a88c05e608c2cce28024041a5b9874013a1e2a/0/76a914119b098e2e980a229e139a9ed01a469e518e6f2688ac/1061/0/0/0

There are 3 trailing /0 s at the end. What is the significance of this? Can it be ignored, it is not explained in the readme. Also is the 1061 before the 3 zeroes the amount? 

Thanks

**Comment by richardkiss** [comment]
Sorry for delay on this. Yes, you can ignore these extra 0s. This is a representation of the `TxOut` as a `Spendable` https://github.com/richardkiss/pycoin/blob/main/pycoin/coins/bitcoin/Spendable.py and mean `block_index_available` (what block created the TxOut), `does_seem_spent` (a boolean) and `block_index_spent` (what block spends the TxOut). 0 means not created/spent.

This may have been a bad idea on my part to expand this.
