### ISSUE TITLE
Trying to produce private/public and addresses to match other apps

### ISSUE THREAD

**Issue by jkugler** [richardkiss/pycoin#357]
I am very new at this, so feel free to slap me with a fish if I'm missing something obvious.

I have a wallet in JAXX. The given address for the wallet is 18onCVuduAJ9UxQ3kX9Q1q9SWVid98s6Ej

I can get a matching address when I recreate the wallet using bip32utils thusly:
```
    mobj = mnemonic.Mnemonic("english")
    seed = mobj.to_seed("my words here")

    bip32_root_key_obj = bip32utils.BIP32Key.fromEntropy(seed)
    bip32_child_key_obj = bip32_root_key_obj.ChildKey(
        44 + bip32utils.BIP32_HARDEN
    ).ChildKey(
        0 + bip32utils.BIP32_HARDEN
    ).ChildKey(
        0 + bip32utils.BIP32_HARDEN
    ).ChildKey(0).ChildKey(0)

    return bip32_child_key_obj.Address()
```
As I said, that will produce an address that matches what I got in JAXX.  However, when I create a key with pycoin (using the same `seed` above, I get something completely different:
```
>>> key = network.keys.bip32_seed(seed)
>>> key.address()
u'1AaGpsYzmaa5bcqQGSmmxgS9HsfP1N9bXw'
```
Incidentally, the private keys don't seem to match either.

Like I said, I'm new at this. I could be doing something totally wrong, and/or completely misunderstanding some fundamental point. Feel free to throw doc links at me. :)

Also: I tried to join Zulip to join the chat, but it said I needed an invite to join the organization...so I'm posting here instead. :(

**Comment by richardkiss** [comment]
Urk, the zulip problem is a mistake. I updated the settings, please try joining now. That explains why traffic has been low.

**Comment by richardkiss** [comment]
In the top example, you're traversing down the tree a few levels. In the pycoin example, you're getting the address at the top of the tree. Try traversing down the BIP32 tree with something like `key.subkey_for_path("44/0H/0H/0/0")`.

**Comment by jkugler** [comment]
Ah, that makes sense. Thanks for the pointers!
