### ISSUE TITLE
BLockCypher broadcast broken - FIX included

### ISSUE THREAD

**Issue by blutooth** [richardkiss/pycoin#358]
Change line 73 from  here:
https://github.com/richardkiss/pycoin/blob/master/pycoin/services/blockcypher.py

From this:
`        result = json.loads(urlopen(url, data=json.dumps(data)).read().decode("utf8"))
` to 

`   result = json.loads(urlopen(url, data=json.dumps(data).encode("utf8")).read().decode("utf8"))
`

**Comment by richardkiss** [comment]
Fixed in 2d22e3f7fb8a65e2bad6808c67aca20b2cd5dd21.
