### ISSUE TITLE
SQLite3 as a requirement

### ISSUE THREAD

**Issue by peter-conalgo** [richardkiss/pycoin#363]
My deployment environment does not have SQLite3 and so importing `keys/KeyChain.py` fails. I have no interest in, nor need for these KeyChain features.

It's not clear to me if it's assured to be a part of a basic Python install.

Production env (FreeBSD):
```
% python
Python 3.6.5 (default, Aug 16 2018, 01:14:45) 
[GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
>>> 
```

**Comment by richardkiss** [comment]
I agree. Submit a pull request that doesn't break things too much and I'll merge it.

**Comment by peter-conalgo** [comment]
Just a comment that this bug bit me again today.

[PR is here](https://github.com/richardkiss/pycoin/pull/368)

**Comment by richardkiss** [comment]
The latest version on pypi has this fix included.
