### ISSUE TITLE
Remove wrapping / in output

### ISSUE THREAD

**Issue by shivaenigma** [richardkiss/pycoin#385]
`wallet key                   : xprv9xWkBDfyBXmZjBG9EiXBpy67KK72fphUp9utJokEBFtjsjiuKUUDF5V3TU8U8c\
                                 DzytqYnSekc8bYuJS8G3bhXxKWB89Ggn2dzLcoJsuEdRK
public version               : xpub6BW6ajCs1uKrwfLcLk4CC72qsLwX5HRLBNqV7C9qjbRikY43s1nTnsoXJiHqef\
                                 fR2sGzH7bCsgmbr6PmVgbXwkKYofppLMweZUNeT7S83tW
`

This causes various problem in using the output:
- Cannot copy and select the xpub / xprv to use it anywhere
- Difficult to write filter scripts to extract the ouput and use it  forward ` ku P:foo | grep "xpub" | awk '{print $2}'`

**Comment by richardkiss** [comment]
For shell scripts, I recommend using `ku -j` to produce json output, and then pipe it through [`jq`](https://stedolan.github.io/jq/) or a similar tool to parse out any text that you need.
