### ISSUE TITLE
How to create network and sign transaction by parameters of network?

### ISSUE THREAD

**Issue by 0ralo** [richardkiss/pycoin#386]
I have lots of parameters that i need to use to send coin. I'm talking about theese parameters(wif_prefix_hex, address_prefix_hex,
pay_to_script_prefix_hex, bip32_prv_prefix_hex and others). How can i send coins throught the netwrok created by theese parameters and how can i connect to network by theese parameters?

**Comment by richardkiss** [comment]
Sorry, I don't understand... what exactly are you trying to do?

**Comment by 0ralo** [comment]
> Sorry, I don't understand... what exactly are you trying to do?

Ok, i'll try to explain. I have task to get hex of signed transaction and use it. I know how to make transaction  in bitcoin but i don't use bitcoin. I use another network and don't know how to connect to it by this library. I have a lot of attributes of my network ( I mean wif_prefix_hex="80", address_prefix_hex="19",
pay_to_script_prefix_hex="32", bip32_prv_prefix_hex="0488ade4",
bip32_pub_prefix_hex="0488B21E", bech32_hrp="bc", bip49_prv_prefix_hex="049d7878",
bip49_pub_prefix_hex="049D7CB2", bip84_prv_prefix_hex="04b2430c",
bip84_pub_prefix_hex="04B24746", magic_header_hex="F1CFA6D3", default_port=3666)
How to create network by these valuest and get hex of signed transaction?

**Comment by richardkiss** [comment]
Look at examples in `pycoin/pycoin/symbols` and use one of those as a template.
