### ISSUE TITLE
Release with P2TR support

### ISSUE THREAD

**Issue by C-Otto** [richardkiss/pycoin#393]
It seems 5717a6bc03436356d512f62694cedbad111e7fe2 adds support for P2TR. Could you please add a tag/release so that this feature can be used in downstream projects (https://github.com/romanz/electrs/issues/683)?

**Comment by richardkiss** [comment]
Now available https://pypi.org/project/pycoin/0.92.20220212/

**Comment by C-Otto** [comment]
Thank you :)
