### ISSUE TITLE
pycoin\ecdsa\__init__.py file is 0KB

### ISSUE THREAD

**Issue by GWNdrew** [richardkiss/pycoin#398]
I have code that calls:
from pycoin.ecdsa import generator_secp256k1, sign, verify
and I get this error:
ImportError: cannot import name 'generator_secp256k1' from 'pycoin.ecdsa' (C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\pycoin\ecdsa\__init__.py)

I checked the pycoin\ecdsa\__init__.py file on my computer and in this repository and it is empty in both places.

Is it supposed to be blank?
Any suggestion on a workaround?

Thank you

**Comment by richardkiss** [comment]
The import you need has moved to `pycoin.ecdsa.secp256k1`. Try

`from pycoin.ecdsa.secp256k1 import generator_secp256k1`

Or use an older version of `pycoin`, prior to Aug. 2017 or so. Probably https://pypi.org/project/pycoin/0.80/ would do it

**Comment by GWNdrew** [comment]
Thank you for quick reply.
In the new version do I still use the ", sign, verify"?  ie:  import secp256k1_generator, sign, verify
If not, will this line of code work:
signature = sign(generator_secp256k1, privKey, msgHash)
Thank you

**Comment by GWNdrew** [comment]
okay I uninstalled pycoin-0.92.20220213 and installed pycoin-0.80
Now my code works 
Too bad that your new code breaks legacy code.
