### ISSUE TITLE
Pycoin does not work with latest Ubuntu (22.04 Jammy) (ripemd160 has been deprecated in OpenSSL-3)

### ISSUE THREAD

**Issue by mmgen** [richardkiss/pycoin#399]
For some background on this situation, see: https://github.com/bitcoin/bitcoin/issues/23710

**Comment by Luned** [comment]
Having the same issue here on my side. Just updated Ubuntu today, and am currently unable to run my project locally. Same with my colleagues who updated.

**Comment by mmgen** [comment]
> Having the same issue here on my side. Just updated Ubuntu today, and am currently unable to run my project locally. Same with my colleagues who updated.

Here's the workaround I came up with for my project: https://github.com/mmgen/mmgen/commit/40d90b37b8786bdf21fee382cee59efc4bfb187f

Call the wrapper routine once with no arguments and then you can use pycoin without any modification.

**Comment by Luned** [comment]
@mmgen Thank you very much for sharing! This worked perfectly.

**Comment by richardkiss** [comment]
Should be fixed in `0.92.20220529` release.
