### ISSUE TITLE
How to generate many addresses from a parent address

### ISSUE THREAD

**Issue by haysquareA** [richardkiss/pycoin#405]
Hello there,
I'm new to pycoin and couldn't get my head around it well yet.
I'm working on a project requiring a parent address with many child addresses that could be used to receive coins.

For example, Address A would be able to create child 1, child 2 and child 3 .....
and those children could be used to receive coins that will go straight to the parent's Address A 
Thanks a lot in advance

**Comment by superswan** [comment]
You are basically looking for HD wallet functionality. The addresses are not cryptographically related to each other. In most wallets that work this way. A single seed determines the generated addresses and their association. Do you have an example of a wallet or blockchain that already has this functionality?

**Comment by haysquareA** [comment]
py_crypto_hd_wallet seems to have.

**Comment by haysquareA** [comment]
> You are basically looking for HD wallet functionality. The addresses are not cryptographically related to each other. In most wallets that work this way. A single seed determines the generated addresses and their association. Do you have an example of a wallet or blockchain that already has this functionality?

py_crypto_hd_wallet seems to have
