### ISSUE TITLE
ImportError: cannot import name 'possible_public_pairs_for_signature'

### ISSUE THREAD

**Issue by Aviksaikat** [richardkiss/pycoin#419]
What is the current way of importing `possible_public_pairs_for_signature` method ?
Got this: `ImportError: cannot import name 'possible_public_pairs_for_signature' from 'pycoin.ecdsa'`

**Comment by richardkiss** [comment]
This is now scoped to the curve (for example, secp256k1).

```
from pycoin.ecdsa import secp256k1

secp256k1.Generator.possible_public_pairs_for_signature(...)
```

Let me know if you need more info.
