### ISSUE TITLE
MultiSig

### ISSUE THREAD

**Issue by mpronk** [richardkiss/pycoin#56]
Hi,

Could you have a look at your MultiSig implementation?

https://github.com/richardkiss/pycoin/blob/master/pycoin/tx/pay_to/ScriptMultisig.py

I am trying to figure out how to transfer BTC to a multisig address and spending it again to another address, however the  ScriptMultisig .address() method does not work. Could you fix it or put me in the right direction?

Thanks in advance,

Machiel

```
Traceback (most recent call last):
  File "multisig.py", line 31, in <module>
    txs_out=TxOut(2, tx.address()),  # Transfer 2 satoshi to multisig addr
  File "...../pycoin/tx/pay_to/ScriptMultisig.py", line 55, in address
    if self._address is None:
AttributeError: 'ScriptMultisig' object has no attribute '_address'
```

**Comment by lekanovic** [comment]
@mpronk do you have an example of how you are spending from a multisig address to a regular address? I have not been successful in doing this yet. Here is some code sample of what I tried so far:

spendables = spendables_for_address("2Mxp1mDd9Hqu3iQcpEWaAHkeHCkHhXnhVSJ")
txs_in = [s.tx_in() for s in spendables]

amount=0
for s in spendables:
    amount += s.coin_value

txs_out = []
script = standard_tx_out_script("mqESpoK2bDzreSNEu2SmH9cQLc4EuYAZL8")
txs_out.append(TxOut(amount, script))

tx = Tx(version=1, txs_in=txs_in, txs_out=txs_out, lock_time=0)
tx.set_unspents(spendables)

# Here is the part that I am not sure how to do
M=3
N=2
hash160_lookup = build_hash160_lookup(key.secret_exponent() for key in wifs)
underlying_script = ScriptMultisig(n=N, sec_keys=[key.sec() for key in keys[:M]]).script()
p2sh_lookup = build_p2sh_lookup([underlying_script])
tx_signed = tx.sign(hash160_lookup=hash160_lookup, p2sh_lookup=p2sh_lookup)

#Error message
  File "bip32.py", line 275, in <module>
    tx_signed = tx.sign(hash160_lookup=hash160_lookup, p2sh_lookup=p2sh_lookup)
  File "/home/navodar/projects/bitcoin-rpc/bitcoin/ENV/local/lib/python2.7/site-packages/pycoin/tx/Tx.py", line 374, in sign
    hash160_lookup, idx, self.unspents[idx].script, hash_type=hash_type, **kwargs)
  File "/home/navodar/projects/bitcoin-rpc/bitcoin/ENV/local/lib/python2.7/site-packages/pycoin/tx/Tx.py", line 232, in sign_tx_in
    b2h(hash160))
ValueError: hash160=3d0c2688671414c3b62d439056edc00ee4b79e4c not found in p2sh_lookup

**Comment by shayanb** [comment]
@lekanovic I had the same issue when I was trying to sign a multisig transaction, what I did was instead of tx.sign(), I used tx_utils.create_signed_tx()

```
 tx_utils.create_signed_tx(spendables_for_address(address), ["1shaYanre36PBhspFL9zG7nt6tfDhxQ4u"], wifs=([key.wif() for key in keys[:M]]), fee=1000, p2sh_lookup=p2sh_lookup)
```

**Comment by lekanovic** [comment]
@shayanb, thanks for your answer. I did try your suggestion but it did not work. I think am not creating the p2sh_lookup correctly when I am redeeming the multisig address.

# In the code below I am using the same keys that I used when I created the multisig address. So 
# this is what I am not understading I am using the same keys.

# This is how I am creating the multisig address.
script = ScriptMultisig(n=N, sec_keys=[key.sec() for key in keys[:M]])
p2sh_lookup = build_p2sh_lookup([script])
for a in p2sh_lookup:
     print b2h(a)
# The output is: 905df2df2707dcb6580e9f4178e087b961a6ca8a

# When I am trying to redeem bitcoins from the multisig address above. The keys that I am using 
# here is the same as the one above.
# What I dont understand here is that I thought that the output from the # code below should give 
# the same output as above.
underlying_script = ScriptMultisig(n=N, sec_keys=[key.sec() for key in keys[:M]]).script()
p2sh_lookup = build_p2sh_lookup([underlying_script])
for a in p2sh_lookup:
     print b2h(a)
# The ouput is: 3d0c2688671414c3b62d439056edc00ee4b79e4c

# Or is this not correct understanding?
