### ISSUE TITLE
tx/script/vm.py:verify_script bytes vs ints in is_p2sh clause

### ISSUE THREAD

**Issue by samrushing** [richardkiss/pycoin#61]
While testing p2sh multisig I tried instrumenting this function.  I noticed the 'is_p2h' clause was failing because it was comparing a char (e.g. script_public_key[0]) against an int (opcodes.OP_HASH160).

repro: "tx -a 485716e53b422aca0fe5b1ded21360695ce5f49255d80e10db56458ed6962ff3"

**Comment by richardkiss** [comment]
Fixed as of 93334719719a6f11144425030594250432b33840.
