### ISSUE TITLE
Scripts; pushing a value 0x100 thru 0xffffff

### ISSUE THREAD

**Issue by peter-conalgo** [richardkiss/pycoin#64]
I haven't checked, but now that I think about it, I think the code for `write_push_data()` in `tx/script/tools.py` will not work well for values that could be encoded into 3 bytes. The script language only supports 1/2/4 byte integers, but the `int_to_bytes()` function is a little too powerful in that it would encode those in 3 bytes.

**Comment by richardkiss** [comment]
This inspired me to write a few new tests of ```write_push_data()``` and I think it is okay now.
