### ISSUE TITLE
Partially signed transactions should use OP_0 as placeholder

### ISSUE THREAD

**Issue by ysobolev** [richardkiss/pycoin#74]
I believe many multisig wallets (CoinVaut, BitGo) use the convention that OP_0 is used as a placeholder for missing signatures. I am not sure if it is a standard, but it does appear to be used in many places. Can ScriptMultisig._dummy_signature please be changed to return "\x00" instead? Thanks.

**Comment by richardkiss** [comment]
I agree that there should be a standard placeholder, but my gut feeling has been to put a 0000...0 signature the same length of a standard signature. This way, a partially signed transaction is exactly the same length as the final transaction, which makes it a bit easier to calculate the required transaction fees. I think this is better than OP_0 even though it doesn't match the defacto "standard" that others have adopted. What do you think?

**Comment by ysobolev** [comment]
Well, you have an excellent point about fees. By the way, right now, the signature is _not_ all zeros. Anyway, if you want to try to champion another standard, I support that. I agree, OP_0 is not exactly the best placeholder. However, if the majority of users settle on OP_0, that is what you should go with.

**Comment by sserrano44** [comment]
I had this same issue trying the cryptocorp api and had to monkey patch pycoin to make it work

**Comment by richardkiss** [comment]
Sebastian, can I take a look at your patch?

**Comment by ysobolev** [comment]
If using 0.53 from GitHub, then the following code works well:
ScriptMultisig._dummy_signature = lambda x, y: "\x00"
If using 0.52, there appears to be a bug and ScriptMultisig.solve needs a rewrite.

**Comment by sserrano44** [comment]
def dummy_signature(sig_type):
    order = generator_secp256k1.order()
    r, s = order - 1, order // 2
    return der.sigencode_der(r, s) + bytes_from_int(sig_type)


def fix_input_script(inp, redeem_script):
    """replace dummy signatures with OP_0 and add redeem script for digitaloracle compatibility"""
    dummy = b2h(dummy_signature(1))
    ops1 = []
    for op in opcode_list(inp.script):
        if op == dummy:
            op = 'OP_0'
        ops1.append(op)
    # FIXME hack to add redeem script omitted by pycoin
    ops1.append(b2h(redeem_script))
    inp.script = compile(' '.join(ops1))

**Comment by richardkiss** [comment]
As of d09b5e0a9a23cae2213f2c46c688ab88f65198a3, you should be able to pass in
```signature_placeholder=OP_0``` as a kwarg to ```Tx.sign``` to use OP_0 as your placeholder.
