### ISSUE TITLE
Calling `verify_tx_in` results in ValidationFailureError/TypeError as of c441ea7

### ISSUE THREAD

**Issue by mbogosian** [richardkiss/pycoin#77]
This worked as of bcdff1f3ead3a5eaeab4460e77b7fd98bd0da321, but fails as of c441ea75885167a809ae402d03e1066ed89d3804 (and still fails as of 412efbced6852b586bca8ba2f34f124c974b29c4).

```python
2015-02-03T21:36:31.77704   File ".../site-packages/pycoin/tx/Tx.py", line 241, in verify_tx_in
2015-02-03T21:36:31.77705     b2h_rev(tx_in.previous_hash), tx_in_idx))
2015-02-03T21:36:31.77705 pycoin.tx.Tx.ValidationFailureError: just signed script Tx ... TxIn index
 0 did not verify
2015-02-03T21:36:31.77706
2015-02-03T21:36:31.82969    ERROR (15598): script failed
2015-02-03T21:36:31.82972 Traceback (most recent call last):
2015-02-03T21:36:31.82973   File ".../site-packages/pycoin/tx/script/vm.py", line 154, in eval_script
2015-02-03T21:36:31.82973     signature_hash = signature_for_hash_type_f(signature_type, script=script)
2015-02-03T21:36:31.82974 TypeError: <lambda>() got an unexpected keyword argument 'script'
```

c441ea75885167a809ae402d03e1066ed89d3804 adds [a keyword parameter](https://github.com/richardkiss/pycoin/commit/c441ea75885167a809ae402d03e1066ed89d3804#diff-77fcdef4fb2acfe71be569ca24cafd78R154) to the call for `signature_for_hash_type_f`.

Not all things pointed to by that symbol accept a `script` argument (note the two `lambda` expressions in `Tx.py`):

```sh
% git co c441ea75885167a809ae402d03e1066ed89d3804
...
% find . -name \*.py | xargs egrep -n 'signature_for_hash_type_f\s*[(=]'
./pycoin/tx/Tx.py:224:        signature_for_hash_type_f = lambda hash_type: self.signature_hash(tx_out_script, tx_in_idx, hash_type)
./pycoin/tx/Tx.py:237:        signature_for_hash_type_f = lambda hash_type: self.signature_hash(tx_out_script, tx_in_idx, hash_type)
./pycoin/tx/Tx.py:339:        def signature_for_hash_type_f(hash_type, script=None):
./pycoin/tx/script/vm.py:121:                signature_hash = signature_for_hash_type_f(signature_type)
./pycoin/tx/script/vm.py:154:                    signature_hash = signature_for_hash_type_f(signature_type, script=script)
```

Two offenders:

* [`Tx.py` at line 224](https://github.com/richardkiss/pycoin/blob/c441ea75885167a809ae402d03e1066ed89d3804/pycoin/tx/Tx.py#L224)
* [`Tx.py` at line 237](https://github.com/richardkiss/pycoin/blob/c441ea75885167a809ae402d03e1066ed89d3804/pycoin/tx/Tx.py#L237)

Only one of them appears to have been addressed in 93334719719a6f11144425030594250432b33840:

```sh
% git co 93334719719a6f11144425030594250432b33840
...
% find . -name \*.py | xargs egrep -n 'signature_for_hash_type_f\s*[(=]'
./pycoin/tx/script/vm.py:121:                signature_hash = signature_for_hash_type_f(signature_type, script=script)
./pycoin/tx/script/vm.py:154:                    signature_hash = signature_for_hash_type_f(signature_type, script=script)
./pycoin/tx/Tx.py:240:        signature_for_hash_type_f = lambda hash_type, script: self.signature_hash(script, tx_in_idx, hash_type)
./pycoin/tx/Tx.py:253:        signature_for_hash_type_f = lambda hash_type: self.signature_hash(tx_out_script, tx_in_idx, hash_type)
./pycoin/tx/Tx.py:354:        signature_for_hash_type_f = lambda hash_type, script: self.signature_hash(script, tx_in_idx, hash_type)
```

Remaining offender after 93334719719a6f11144425030594250432b33840:

* [`Tx.py` at line 253](https://github.com/richardkiss/pycoin/blob/93334719719a6f11144425030594250432b33840/pycoin/tx/Tx.py#L253)

I'm not sure how tests are still passing with this? :confused:

**Comment by mbogosian** [comment]
By the way, this seemed to have been working briefly as of 00806d91edcf8538502a618bea80044f6802129d, but broke again shortly thereafter (I'm not sure with which commit).

**Comment by richardkiss** [comment]
Can you see if this fixes your issue?

**Comment by mbogosian** [comment]
This is basically the same thing as my proposal in #78, so if you're happy with it and @gitmarek is happy with it, I'm happy with it. :+1: The exception I was experiencing no longer occurs with this change.
