### ISSUE TITLE
Fixed in PR #99 - Call to `script_obj_from_address` from `standard_tx_out_script` doesn't use `netcodes` argument

### ISSUE THREAD

**Issue by mbogosian** [richardkiss/pycoin#85]
See [here](https://github.com/richardkiss/pycoin/blob/8e7a87c8c416ab85238d46522a5f7ea55abcdf73/pycoin/tx/TxOut.py#L70). I'm pretty sure it should be this instead:

```python
def standard_tx_out_script(address, netcodes=DEFAULT_NETCODES):
    script_obj = script_obj_from_address(address, netcodes=netcodes)
    if script_obj is None:
        raise ValueError("can't parse address %s" % address)
    return script_obj.script()
```

I'm on the road, but I'll submit a patch when I can (unless someone else gets to it first).

**Comment by shayanb** [comment]
https://github.com/richardkiss/pycoin/pull/86
